### ISSUE TITLE
virus scan: ignored, temporary fail

### ISSUE THREAD

**Issue by ddeenniiss** [vstakhov/rmilter#101]
Hi,

I configured rspamd with rmilter, everything works.

But when I added clamav , I get the following message, 

Apr 25 14:38:02 tintamarre rmilter[9789]: <717FA25201C> clamscan: start scanning message on /var/run/clamav/clamd.ctl
Apr 25 14:38:02 tintamarre rmilter[9789]: clamav: <717FA25201C>: paths differ: 'stream: Eicar-Test-Signature FOUND#012' instead of '#005'
Apr 25 14:38:02 tintamarre rmilter[9789]: <717FA25201C> clamscan: finish scanning message on /var/run/clamav/clamd.ctl
Apr 25 14:38:02 tintamarre rmilter[9789]: clamscan: <717FA25201C>: retry limit exceeded, /var/run/clamav/clamd.ctl, /tmp/msg.XXBg1qAK
Apr 25 14:38:02 tintamarre rmilter[9789]: clamscan: <717FA25201C>: scan 4.012954, /var/run/clamav/clamd.ctl, /tmp/msg.XXBg1qAK

Any Ideas ?

**Comment by vstakhov** [comment]
Do you use `1.8.1`?

**Comment by ddeenniiss** [comment]
Yes, 1.8.1.

I tried to understand, if clamav installed I have no problems but if I want to test the detection of viruses with http://www.emailsecuritycheck.net nothing is detected and all is fine.

Apr 28 20:42:23 tintamarre rmilter[32351]: msg done: E5DE11C18C: ip: 149.202.232.193; from: <securitycheck@emailsecuritycheck.net>; rcpt: <xxx@xxx.be> (1 total); user: unauthorized; spam scan: no spam; virus scan: clean; dkim: not signed, ignored

So I added clamav unofficial sigs, but when clamav finds a virus, something crash.

Apr 28 20:46:49 tintamarre rmilter[32351]: msg done: 02FB01C18C: ip: 149.202.232.193; from: <securitycheck@emailsecuritycheck.net>; rcpt: <xxx@xxx.be> (1 total); user: unauthorized; spam scan: no spam; virus scan: ignored, temporary fail; dkim: not signed, ignored

**Comment by vstakhov** [comment]
That should be fixed in 1.8.2, thank you.

**Comment by vstakhov** [comment]
Grr, in fact, that was fixed in 1.8.3

**Comment by ddeenniiss** [comment]
Thanks, working fine !
