### ISSUE TITLE
rmilter 1.8.3 crash

### ISSUE THREAD

**Issue by mnik247** [vstakhov/rmilter#103]
**system:**
-CentOS release 6.7 (Final)
-Linux 2.6.32-504.8.1.el6.x86_64 #1 SMP Wed Jan 28 21:11:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
-postfix (mail_version = 2.11.1)
-rmilter-1.8.3
-rspamd-1.2.6

**/var/log/messages:**
Apr 30 14:21:48 zm kernel: rmilter[30332]: segfault at 40 ip 000000000041a039 sp 00007f2209bc37b0 error 4 in rmilter[400000+57000]

**/var/log/maillog:**
Apr 30 14:21:41 zm postfix/smtpd[30329]: connect from unknown[103.242.209.118]
Apr 30 14:21:42 zm postfix/smtpd[30329]: NOQUEUE: filter: RCPT from unknown[103.242.209.118]: <Smith_Wanda@bellevernonpa.com>: Sender address triggers FILTER
 smtp-amavis:[127.0.0.1]:10026; from=<Smith_Wanda@bellevernonpa.com> to=<office@domain.com.ua> proto=SMTP helo=<192.168.22.30>
Apr 30 14:21:42 zm postfix/smtpd[30329]: NOQUEUE: filter: RCPT from unknown[103.242.209.118]: <Smith_Wanda@bellevernonpa.com>: Sender address triggers FILTER
 smtp-amavis:[127.0.0.1]:10024; from=<Smith_Wanda@bellevernonpa.com> to=<office@domain.com.ua> proto=SMTP helo=<192.168.22.30>
Apr 30 14:21:42 zm postfix/smtpd[30329]: DF80A80098: client=unknown[103.242.209.118]
Apr 30 14:21:44 zm postfix/cleanup[30338]: DF80A80098: message-id=<429883h0ocl8$sm4m7w57$6097v1u4@FY763609498736>
Apr 30 14:21:44 zm rmilter[2913]: mlfi_eom: DF80A80098: tempfile=/tmp/msg.XXvlZTJ2, size=17639
Apr 30 14:21:44 zm rmilter[2913]: <DF80A80098> spamdscan: start scanning message on localhost
Apr 30 14:21:48 zm rmilter[2913]: <DF80A80098> spamdscan: finish scanning message on localhost
Apr 30 14:21:48 zm rmilter[2913]: spamdscan: <DF80A80098> too large reply: 1338, skip options
Apr 30 14:21:48 zm postfix/cleanup[30338]: warning: milter inet:127.0.0.1:11332: can't read SMFIC_BODYEOB reply packet header: Success
Apr 30 14:21:48 zm postfix/qmgr[10460]: DF80A80098: from=<Smith_Wanda@bellevernonpa.com>, size=17731, nrcpt=1 (queue active)
Apr 30 14:21:48 zm postfix/amavisd/smtpd[30343]: connect from localhost.localdomain[127.0.0.1]
Apr 30 14:21:48 zm postfix/amavisd/smtpd[30343]: 8D9CC800C7: client=localhost.localdomain[127.0.0.1]
Apr 30 14:21:48 zm postfix/cleanup[30338]: 8D9CC800C7: message-id=<429883h0ocl8$sm4m7w57$6097v1u4@FY763609498736>
Apr 30 14:21:48 zm postfix/qmgr[10460]: 8D9CC800C7: from=<Smith_Wanda@bellevernonpa.com>, size=18239, nrcpt=1 (queue active)
Apr 30 14:21:48 zm postfix/amavisd/smtpd[30343]: disconnect from localhost.localdomain[127.0.0.1]
Apr 30 14:21:48 zm postfix/smtp[30340]: DF80A80098: to=<nm@domain.com>, orig_to=<office@domain.com.ua>, relay=127.0.0.1[127.0.0.1]:10024, delay
=6.3, delays=6.1/0.02/0/0.18, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 8D9CC800C7)
Apr 30 14:21:48 zm postfix/qmgr[10460]: DF80A80098: removed
Apr 30 14:21:48 zm postfix/lmtp[30344]: 8D9CC800C7: to=<nm@domain.com>, relay=zm.domain.com[192.168.22.30]:7025, delay=0.24, delays=0.01/0.0
2/0.13/0.08, dsn=2.1.5, status=sent (250 2.1.5 Delivery OK)
Apr 30 14:21:48 zm postfix/qmgr[10460]: 8D9CC800C7: removed
Apr 30 14:21:48 zm postfix/smtpd[30329]: disconnect from unknown[103.242.209.118]

**/var/log/rspamd/rspamd.log:**
2016-04-30 14:21:44 #1823(normal) <253b34>; task; accept_socket: accepted connection from 127.0.0.1 port 42704
2016-04-30 14:21:44 #1823(normal) <253b34>; task; rspamd_message_parse: loaded message; id: <429883h0ocl8$sm4m7w57$6097v1u4@FY763609498736>; queue-id: <DF80A
80098>
2016-04-30 14:21:44 #1823(normal) <253b34>; lua; settings.lua:226: check for settings
2016-04-30 14:21:45 #1823(normal) <253b34>; task; process_dns_results: <429883h0ocl8$sm4m7w57$6097v1u4@FY763609498736> domain [earthgi.com.multi.surbl.org] i
s in surbl multi.surbl.org(40)
2016-04-30 14:21:45 #1823(normal) <253b34>; task; process_dns_results: <429883h0ocl8$sm4m7w57$6097v1u4@FY763609498736> domain [earthgi.com.multi.surbl.org] i
s in surbl multi.surbl.org(4)
2016-04-30 14:21:45 #1823(normal) <253b34>; task; process_dns_results: <429883h0ocl8$sm4m7w57$6097v1u4@FY763609498736> domain [comajci.org.multi.uribl.com] i
s in surbl multi.uribl.com(2)
2016-04-30 14:21:45 #1823(normal) <253b34>; task; process_dns_results: <429883h0ocl8$sm4m7w57$6097v1u4@FY763609498736> domain [ipaem.com.multi.surbl.org] is
in surbl multi.surbl.org(40)
2016-04-30 14:21:45 #1823(normal) <253b34>; task; process_dns_results: <429883h0ocl8$sm4m7w57$6097v1u4@FY763609498736> domain [ipaem.com.multi.surbl.org] is
in surbl multi.surbl.org(4)
2016-04-30 14:21:45 #1823(normal) <253b34>; task; process_dns_results: <429883h0ocl8$sm4m7w57$6097v1u4@FY763609498736> domain [bracecodes.com.dbl.spamhaus.or
g] is in surbl dbl.spamhaus.org(201007f)
2016-04-30 14:21:45 #1823(normal) <253b34>; task; process_dns_results: <429883h0ocl8$sm4m7w57$6097v1u4@FY763609498736> domain [ipaem.com.multi.uribl.com] is
in surbl multi.uribl.com(2)
2016-04-30 14:21:45 #1823(normal) <253b34>; task; process_dns_results: <429883h0ocl8$sm4m7w57$6097v1u4@FY763609498736> domain [bracecodes.com.multi.surbl.org
] is in surbl multi.surbl.org(40)
2016-04-30 14:21:45 #1823(normal) <253b34>; task; process_dns_results: <429883h0ocl8$sm4m7w57$6097v1u4@FY763609498736> domain [bracecodes.com.multi.surbl.org
] is in surbl multi.surbl.org(4)
2016-04-30 14:21:45 #1823(normal) <253b34>; task; process_dns_results: <429883h0ocl8$sm4m7w57$6097v1u4@FY763609498736> domain [bracecodes.com.multi.uribl.com
] is in surbl multi.uribl.com(2)
2016-04-30 14:21:45 #1823(normal) <253b34>; task; process_dns_results: <429883h0ocl8$sm4m7w57$6097v1u4@FY763609498736> domain [earthgi.com.dbl.spamhaus.org]
is in surbl dbl.spamhaus.org(201007f)
2016-04-30 14:21:45 #1823(normal) <253b34>; task; process_dns_results: <429883h0ocl8$sm4m7w57$6097v1u4@FY763609498736> domain [comajci.org.multi.surbl.org] i
s in surbl multi.surbl.org(40)
2016-04-30 14:21:45 #1823(normal) <253b34>; task; process_dns_results: <429883h0ocl8$sm4m7w57$6097v1u4@FY763609498736> domain [comajci.org.multi.surbl.org] i
s in surbl multi.surbl.org(4)
2016-04-30 14:21:45 #1823(normal) <253b34>; task; process_dns_results: <429883h0ocl8$sm4m7w57$6097v1u4@FY763609498736> domain [earthgi.com.multi.uribl.com] i
s in surbl multi.uribl.com(2)
2016-04-30 14:21:45 #1823(normal) <253b34>; task; process_dns_results: <429883h0ocl8$sm4m7w57$6097v1u4@FY763609498736> domain [comajci.org.dbl.spamhaus.org]
is in surbl dbl.spamhaus.org(201007f)
2016-04-30 14:21:45 #1823(normal) <253b34>; task; process_dns_results: <429883h0ocl8$sm4m7w57$6097v1u4@FY763609498736> domain [ipaem.com.dbl.spamhaus.org] is
 in surbl dbl.spamhaus.org(201007f)
2016-04-30 14:21:46 #1823(normal) <253b34>; task; process_dns_results: <429883h0ocl8$sm4m7w57$6097v1u4@FY763609498736> domain [comajci.org.uribl.spameatingmo
nkey.net] is in surbl uribl.spameatingmonkey.net(2)
2016-04-30 14:21:46 #1823(normal) <253b34>; task; process_dns_results: <429883h0ocl8$sm4m7w57$6097v1u4@FY763609498736> domain [earthgi.com.uribl.spameatingmo
nkey.net] is in surbl uribl.spameatingmonkey.net(2)
2016-04-30 14:21:46 #1823(normal) <253b34>; task; process_dns_results: <429883h0ocl8$sm4m7w57$6097v1u4@FY763609498736> domain [bracecodes.com.uribl.spameatin
gmonkey.net] is in surbl uribl.spameatingmonkey.net(2)
2016-04-30 14:21:48 #1823(normal) <253b34>; task; process_dns_results: <429883h0ocl8$sm4m7w57$6097v1u4@FY763609498736> domain [ipaem.com.uribl.spameatingmonk
ey.net] is in surbl uribl.spameatingmonkey.net(2)
2016-04-30 14:21:48 #1823(normal) <253b34>; task; rspamd_task_write_log: id: <429883h0ocl8$sm4m7w57$6097v1u4@FY763609498736>, qid: <DF80A80098>, ip: 103.242.
209.118, from: <smith_wanda@bellevernonpa.com>, (default: T (reject): [150.27/19.00] [RBL_SEM,LOCAL_BL_RCPT,RBL_SPAMHAUS_XBL_ANY,MIME_HTML_ONLY,WS_SURBL_MULT
I,HTML_SHORT_LINK_IMG_1,RBL_SPAMHAUS_XBL,RBL_SPAMHAUS_CSS,RBL_UCEPROTECT_LEVEL1,DBL_SPAM,ABUSE_SURBL,FORGED_RECIPIENTS,URIBL_BLACK,RBL_MAILSPIKE_WORST,HFILTE
R_FROMHOST_NORES_A_OR_MX,RBL_SORBS_RECENT,SEM_URIBL,RDNS_NONE,BAYES_HAM,HFILTER_HELO_BAREIP,PHISHING,HFILTER_HOSTNAME_UNKNOWN,RBL_SORBS_WEB,RBL_SENDERSCORE])
, len: 17639, time: 3589.999ms real, 13.421ms virtual, dns req: 59

**bt:**
gdb /usr/sbin/rmilter -c /tmp/core-rmilter-11-496-4-2913-1462015308
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-83.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/sbin/rmilter...Reading symbols from /usr/lib/debug/usr/sbin/rmilter.debug...done.
done.
[New Thread 30332]
[New Thread 2914]
[New Thread 2916]
[New Thread 2913]
Missing separate debuginfo for
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/71/a96b79419fe40ff1706d59ed06d6dbe37c8e97
Reading symbols from /lib64/libresolv.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libresolv.so.2
Reading symbols from /usr/lib64/libssl.so.10...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libssl.so.10
Reading symbols from /usr/lib64/libcrypto.so.10...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libcrypto.so.10
Reading symbols from /lib64/libpcre.so.0...(no debugging symbols found)...done.
Loaded symbols for /lib64/libpcre.so.0
Reading symbols from /usr/lib64/libmilter.so.1.0...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libmilter.so.1.0
Reading symbols from /usr/lib64/libmemcached.so.2...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libmemcached.so.2
Reading symbols from /usr/lib64/libopendkim.so.10...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libopendkim.so.10
Reading symbols from /lib64/libm.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libm.so.6
Reading symbols from /lib64/libpthread.so.0...(no debugging symbols found)...done.
[Thread debugging using libthread_db enabled]
Loaded symbols for /lib64/libpthread.so.0
Reading symbols from /lib64/libc.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libc.so.6
Reading symbols from /lib64/libgssapi_krb5.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libgssapi_krb5.so.2
Reading symbols from /lib64/libkrb5.so.3...(no debugging symbols found)...done.
Loaded symbols for /lib64/libkrb5.so.3
Reading symbols from /lib64/libcom_err.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libcom_err.so.2
Reading symbols from /lib64/libk5crypto.so.3...(no debugging symbols found)...done.
Loaded symbols for /lib64/libk5crypto.so.3
Reading symbols from /lib64/libdl.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libdl.so.2
Reading symbols from /lib64/libz.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libz.so.1
Reading symbols from /usr/lib64/libbsd.so.0...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libbsd.so.0
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2
Reading symbols from /lib64/libkrb5support.so.0...(no debugging symbols found)...done.
Loaded symbols for /lib64/libkrb5support.so.0
Reading symbols from /lib64/libkeyutils.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libkeyutils.so.1
Reading symbols from /lib64/libselinux.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libselinux.so.1
Reading symbols from /lib64/libnss_files.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libnss_files.so.2
Core was generated by `/usr/sbin/rmilter -c /etc/rmilter/rmilter.conf.sysvinit'.
Program terminated with signal 11, Segmentation fault.
#0  rmilter_spamd_symcmp (_ctx=0x1310f80, priv=0x7f21fc0008c0, cfg=0x12fe040, subject=0x7f2209bc3bb8, extra=0)
    at /usr/src/debug/rmilter-1.8.3/src/libspamd.c:149
149             return fabs (s2->score) - fabs (s1->score);
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.166.el6_7.7.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-42z1.el6_7.x86_64 libbsd-0.6.0-1.el6.x86_64 libcom_err-1.41.12-22.el6.x86_64 libmemcached-0.31-1.1.el6.x86_64 libopendkim-2.10.3-1.el6.x86_64 libselinux-2.0.94-5.8.el6.x86_64 openssl-1.0.1e-42.el6_7.4.x86_64 pcre-7.8-7.el6.x86_64 sendmail-milter-8.14.4-9.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt full
#0  rmilter_spamd_symcmp (_ctx=0x1310f80, priv=0x7f21fc0008c0, cfg=0x12fe040, subject=0x7f2209bc3bb8, extra=0)
    at /usr/src/debug/rmilter-1.8.3/src/libspamd.c:149
No locals.
#1  spamdscan (_ctx=0x1310f80, priv=0x7f21fc0008c0, cfg=0x12fe040, subject=0x7f2209bc3bb8, extra=0) at /usr/src/debug/rmilter-1.8.3/src/libspamd.c:542
        _ls_p = 0x7f21fc0056a0
        _ls_tail = 0x0
        _ls_qsize = 1
        _ls_q = 0x30
        _ls_e = <value optimized out>
        _ls_insize = <value optimized out>
        _ls_nmerges = 1
        _ls_psize = 1
        _ls_i = <value optimized out>
        _ls_looping = <value optimized out>
        retry = <value optimized out>
        r = 0
        to_trace = 0
        i = <value optimized out>
        j = <value optimized out>
        ret = <value optimized out>
        t = {tv_sec = 1462015308, tv_usec = 323087}
        ts = 1462015304.7323608
        tf = 3.5906720161437988
        selected = 0x12fe818
        bar_buf = "\300\071\274\t\"\177\000\000\230*\a\r\"\177\000\000xxxxxxxx \000\000\374!\177\000\000\033\000\000\000\000\000\000\000`\016\000\374!\177\000\000\345\017\000\374!\177\000\000\347D", '\000' <repeats 14 times>, "Ӻ\376\f\"\177\000\000\000\000\000\000\000\000\000\000\340!\000\374!\177\000\000\343\017\000\000\000\000\000\000\000\360\251\016\"\177\000\000\345\017\000\374!\177\000\000\205\320\376\f\"\177\000"
        hdrbuf = ",\000\000\000\025\000\000\000\016\000\000\000\036\000\000\000\003\000\000\000t\000\000\000\006\000\000\000x\000\000\000\001\000\000\000\000\000\000\000\060*\000\000\000\000\000\000\220\235\060\001\000\000\000\000\300\071\274\t\"\177\000\000\000\071\274\t\"\177", '\000' <repeats 18 times>, "@t0\r\"\177\000\000\027\000\000\000\000\000\000\000i\000\000\000\000\000\000\000!\000\000\000\000\000\000\000f\000\000\000\000\000\000\000\260\070\000\374!\177", '\000' <repeats 18 times>, "_\000\000\000\000\000\000\000\260\070\000\374!\177\000\000H\225$W\000\000\000\000A\000\000\000\000\000\000\000\300\b\000\374!\177\000\000`\016\000\374!\177\000\000\200\017\061\001\000\000\000\000\345\017\000\374!\177\000\000\374v\336\r\"\177\000\000\n\000\000\000\000\000\000\000\063\360\005"...
        prefix = 0x445a9d "rs"
        mid = 0x0
        c = <value optimized out>
        res = {obj = 0x7f21fc005ab0, metric_name = 0x0, subject = 0x0, score = 150.279866, required_score = 19, reject_score = 0,
          action = METRIC_ACTION_REJECT, symbols = 0x0}
        cur_symbol = <value optimized out>
        tmp_symbol = <value optimized out>
        sleep_ts = {tv_sec = 1, tv_nsec = 0}
        ctx = 0x1310f80
        optbuf = 0x7f21fc009e78 ""
        logbuf = 0x7f21fc004298 "spamdscan: scan <DF80A80098>, 3.591, localhost, metric: default: [150.280 / 19.000], symbols: "
        headerbuf = 0x7f21fc003b78 "default: True [150.28 / 19.00]\n"
---Type <return> to continue, or q <return> to quit---
        extended_options = false
        print_symbols = true
#2  0x000000000041e247 in mlfi_eom (ctx=0x1310f80) at /usr/src/debug/rmilter-1.8.3/src/rmilter.c:1265
        priv = 0x7f21fc0008c0
        r = <value optimized out>
        er = <value optimized out>
        strres = "\340!\000\374!\177\000\000\250\377\377\377\377\377\377\377s\000\000\000\000\000\000\000\004", '\000' <repeats 15 times>, "b\256\376\f\"\177\000\000\340!\000\374!\177\000\000\t\000\000\000\000\000\000\000\340!\000\374!\177\000\000\245\a\376\f\"\177\000\000\315݅x\000\000\000\000\300\b\000\374!\177\000\000\t\000\000\000\000\000\000\000\345\017\000\374!\177\000\000@$\000\374!\177\000\000\300\b\000\374!\177\000\000\t\000\000\000\000\000\000\000ĽA\000\000\000\000\000/tmp/msg.XXXXXXXX\000\000\000\000\000\000\000\377\377\377\377", '\000' <repeats 12 times>"\370, \064\000\374!\177\000\000\020M\274\t\"\177\000\000\300\066\000\374!\177\000\000\000\020\000\000\000\000\000\000\006\003\376\f\"\177\000\000\002\312\000\000\000\000\000\000w\375\001\000\000\000\000\000\001\000\000\000\000\000\000\000\244"...
        buf = '\000' <repeats 1857 times>, "J\274\t\"\177\000\000\360I\274\t\"\177\000\000\004\000\000\000\000\000\000\000pK\274\t\"\177\000\000s\273D\000\000\000\000\000g\341\373\f\"\177\000\000\200\273D\000\000\000\000\000\r", '\000' <repeats 55 times>"\340, H\274\t\"\177\000\000\000\000\000\000\000\000\000\000q\273D", '\000' <repeats 29 times>, "LI\274\t\"\177\000\000hI\274\t\"\177\000\000\000\000\000\000\000\000\000\000\210I\274\t\"\177\000\000\000\000\000\000\000\000\000\000\320D\377\f\"\177", '\000' <repeats 42 times>"\320, D\274\t\"\177\000\000\377\377\377\377\377\377\377\377@I\274\t\"\177\000\000\000\000\000\000\000\000\000\000\320D\377\f\"\177\000\000\017\000\000\000\000\000\000\000\340!\000\374!\177\000\000\000\000\000\000\000\000\000\000\017\000\000\000\000\000\000\000\230"...
        tmpbuf = '\000' <repeats 97 times>, "\001", '\000' <repeats 29 times>
        ip_str = '\000' <repeats 46 times>
        id = <value optimized out>
        subject = 0x0
        prob_max = <value optimized out>
        prob_cur = <value optimized out>
        sb = {st_dev = 51714, st_ino = 131403, st_nlink = 1, st_mode = 33152, st_uid = 496, st_gid = 4, __pad0 = 0, st_rdev = 0, st_size = 17639,
          st_blksize = 4096, st_blocks = 40, st_atim = {tv_sec = 1462015304, tv_nsec = 729978517}, st_mtim = {tv_sec = 1462015304, tv_nsec = 731978509},
          st_ctim = {tv_sec = 1462015304, tv_nsec = 731978509}, __unused = {0, 0, 0}}
        act = <value optimized out>
        rcpt = <value optimized out>
        ip_whitelisted = <value optimized out>
        ret = 0
        spam_check_result = 0x44b584 "unknown"
        av_check_result = 0x44b584 "unknown"
        dkim_result = <value optimized out>
        addr = <value optimized out>
        hdr = <value optimized out>
        len = 0
#3  0x00007f220dbe0647 in ?? () from /usr/lib64/libmilter.so.1.0
No symbol table info available.
#4  0x00007f220dbe08d2 in mi_engine () from /usr/lib64/libmilter.so.1.0
No symbol table info available.
#5  0x00007f220dbe2838 in mi_handle_session () from /usr/lib64/libmilter.so.1.0
No symbol table info available.
#6  0x00007f220dbe1379 in ?? () from /usr/lib64/libmilter.so.1.0
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#7  0x00007f220d315aa1 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#8  0x00007f220d06293d in clone () from /lib64/libc.so.6
No symbol table info available.

**Comment by mnik247** [comment]
Crash fixed (I hope) in version 1.8.4
I have one email, which can crash rmilter 1.8.3, but can't 1.8.4.

**Comment by vstakhov** [comment]
Could you please show how it is shown in rmilter logs. This code is kind of terra incognita for me, as I have no testing environment for rmilter.

**Comment by mnik247** [comment]
What do you mean "rmilter logs"? 
Now I have milter logs in maillog, and I posted it bellow for 1.8.3
