### ISSUE TITLE
Log connections

### ISSUE THREAD

**Issue by wociscz** [vstakhov/rmilter#121]
Hi, it should be nice to have connection info in log.
I'm using rmilter&rspamd&clamav as a "central" antispam solution for more mtas.
And finding which mailserver check which mail is little bit frustrating :)

something like rmilter[pid]: <xxxx>; connect from: ip... would be perfect.
Thanks!

**Comment by andypl78** [comment]
Also I begin to use it as a central system and would find this option.

**Comment by wociscz** [comment]
Hi, looks good, but :-) now I see originating client ip in the log - it's good information - but there should be information which email server originating connection to rmilter. 
With original client ip in the log - i am still not able to recognise which of my email MTAs checking specific email on rmilter.
(i can't find your paypal address for donations, pm me - i'll send some beers)
