### ISSUE TITLE
rmilter stops working after "can't read SMFIC_BODYEOB reply packet header: Success"

### ISSUE THREAD

**Issue by wackerm** [vstakhov/rmilter#123]
Since the last update(s) rmilter stops working quite often while running and does refuse connections:
`warning: connect to Milter service unix:/var/run/rmilter/rmilter.sock: Connection refused` 

I traced down the last messages from rmilter before it stops working:

```
Jun  3 22:57:12 mail rmilter[20387]: <87cd85a936>; mlfi_eom: tempfile=/tmp/msg.XXSOokki, size=2063
Jun  3 22:57:12 mail rmilter[20387]: <87cd85a936>; spamdscan: start scanning message on localhost
Jun  3 22:57:20 mail postfix/cleanup[12274]: warning: milter unix:/var/run/rmilter/rmilter.sock: can't read SMFIC_BODYEOB reply packet header: Success
[...]
Jun  3 22:57:21 mail postfix/smtp/smtpd[11581]: warning: connect to Milter service unix:/var/run/rmilter/rmilter.sock: Connection refused
```

After manually restarting rmilter, it keeps working for some hours and stops again.

`rmilter -v 
Rapid Milter Version 1.8.5`
##

**Comment by jhuldtgren** [comment]
I'm seeing the same issue, albeit with a slightly differnt error message, however the result is the same, after rmilter hits an "can't read SMFIC_*" error it dies and will need to be restarted. I grepped through my logs and here are all the instances of it I found since November:

```
Nov  3 00:27:49 mail postfix/cleanup[88734]: warning: milter inet:127.0.0.1:9900: can't read SMFIC_HEADER reply packet header: Undefined error: 0
Dec 27 08:29:21 mail postfix/cleanup[78691]: warning: milter inet:127.0.0.1:9900: can't read SMFIC_HEADER reply packet header: Undefined error: 0
Jan  8 07:55:14 mail postfix/cleanup[98364]: warning: milter inet:127.0.0.1:9900: can't read SMFIC_HEADER reply packet header: Undefined error: 0
Jan 21 17:55:07 mail postfix/smtpd[48851]: warning: milter inet:127.0.0.1:9900: can't read SMFIC_CONNECT reply packet header: Undefined error: 0
Jan 24 04:44:32 mail postfix/cleanup[71659]: warning: milter inet:127.0.0.1:9900: can't read SMFIC_HEADER reply packet header: Undefined error: 0
Feb  2 12:34:50 mail postfix/cleanup[37125]: warning: milter inet:127.0.0.1:9900: can't read SMFIC_HEADER reply packet header: Undefined error: 0
```

rmilter -v
Rapid Milter Version 1.10.0

uname -rsvp
OpenBSD 6.0 GENERIC.MP#150 amd64

**Comment by tleuxner** [comment]
`Jun 24 23:08:56 edi postfix/mx-in/cleanup[25091]: warning: milter unix:public/rspamd: can't read SMFIC_BODYEOB reply packet header: Success`

`Jun 24 23:08:56 edi rspamd[25433]: <26b431>; proxy; proxy_milter_error_handler: abnormally closing milter connection from: /var/spool/postfix/public/rspamd, error: invalid header command (no name)`

This still happens occasionally with 1.6.1-2~jessie

**Comment by vstakhov** [comment]
How is it related to Rmilter?
