### ISSUE TITLE
Include original subject when rewriting spam subject

### ISSUE THREAD

**Issue by maethor** [vstakhov/rmilter#124]
Hi,

In rspamd I'm using `rewrite_subject = 6;` to enable subject rewriting when an email is detected as a Spam. Sadly, the subject of the email is not just marked, but entirely replaced by "***SPAM***". So we lost the original subject. Is there a way to just prefix the subject, like we do with amavis/spamassassin?

I don't know if this is a rmilter or rspamd issue. I believe it is rmilter that modifies the email.

Thanks.

**Comment by maethor** [comment]
So you are saying we should not use `rewrite_subject` at all?

Moreover, I believe breaking dkim signature of spam is not a problem, don't you agree?

**Comment by xpunkt** [comment]
no just make it beter, eg if mails is dkim valid pass, dont modify signed headers or body if forwards is wanted, if mails is not forwarded its ok to modify as needed

**Comment by maethor** [comment]
I don't see how what you are saying is answering my question…

Anyway, I find my answer here https://github.com/vstakhov/rspamd/issues/650#issuecomment-224278280

Thanks,
