### ISSUE TITLE
How to DKIM sign mail from abc.com with the generic key of xyz.com ?

### ISSUE THREAD

**Issue by mailjol** [vstakhov/rmilter#126]
Can't figure out how to do this with rmilter. Also I can't find a way to sign all mails (match all domains) using the same key.

**Comment by vstakhov** [comment]
There is no such possibility now in rmilter.

**Comment by mailjol** [comment]
Ok. Thanks for confirming.

**Comment by vstakhov** [comment]
In fact, that could be easily implemented.

**Comment by xpunkt** [comment]
i think this ticket is fixed, see how to in rmilter domainname and keys is not hard to mix

but it would make more sense to make ATPS working in rmilter

**Comment by mailjol** [comment]
Well I closed this issue after receiving confirmation that this feature doesn't exist in rmilter as yet. Cross signing is a essential requirement for me. From a developer point of view it might be a trivial thing to implement and I will be revisiting rmilter to see what future versions bring up. But will have to settle with opendkim for the time being, at-least for the purpose of DKIM signing.
