### ISSUE TITLE
rmilter error: greylisting forever

### ISSUE THREAD

**Issue by wackerm** [vstakhov/rmilter#127]
Hi, i have a problem, since the last updates in rmilter there are no greylisting keys saved in redis so that each message is greylisted forever.

```
redis 127.0.0.1:6379> keys grey*
(empty list or set)
```
It was working before...

Is this a bug or a configuration error?

**Comment by vstakhov** [comment]
What version have you used before?

**Comment by wackerm** [comment]
At the moment i am using

rmilter -v
Rapid Milter Version 1.8.6

Last known working was 1.8.4 and maybe also 1.8.5 (not sure)

**Comment by vstakhov** [comment]
I don't observe this issue with 1.8.6.

**Comment by wackerm** [comment]
Is there any chance to turn greylisting completely off in rmilter/rspamd?

**Comment by vstakhov** [comment]
You can comment out the whole greylisting section. Thought, I'd prefer to figure out what is the problem.

**Comment by moisseev** [comment]
@vstakhov In fact he can't just comment it out. Do you remember https://github.com/vstakhov/rmilter/issues/78 ? And it's very confusing. Would you consider to set `expire=0` by default in rmilter code and set non-zero default in configuration file supplied with rspamd if you want greylisting out of the box?

**Comment by wackerm** [comment]
i switched off greylisting by commenting out servers_grey in the redis section

**Comment by vstakhov** [comment]
@wackerm, do you have anything useful in rmilter logs? I really want to fix this issue if it takes place.

**Comment by wackerm** [comment]
in the mail.log everything looks perfectly well and i can see the rmilter greylisted keys, but every entry has `0 seconds passed (new record)` and if i look into the redis keys there are no grey.* keys at all:
```
redis 127.0.0.1:6379> keys grey*
(empty list or set)
```
it seems to be a problem while saving greylisted keys to redis-server (localhost).
There are no connection issues, since other records are being saved...

**Comment by vstakhov** [comment]
It might be useful to monitor trafic being sent between rmilter and redis to ensure where is the source of the problem.

**Comment by wackerm** [comment]
I monitored the redis traffic quite a while now and i cannot find any SET commands:
When a greylisting action takes place, i can always trace only two `GET` requests:
```
root@mail:/etc# redis-cli monitor | grep -Ei ' "(g|s)et" '

1467137685.695380 "GET" "white.vDm6DslCUmL/...=="
1467137685.695744 "GET" "grey.vDm6DslCUmL/...=="
1467137685.696394 "GET" "white.ROd5cZVgl...=="
1467137685.696638 "GET" "grey.ROd5cZVgl...=="
```
(i have shortened the keys)
I am also using limits and even there appear no `SET` commands ...

**Comment by vstakhov** [comment]
Which version of redis do you use?

**Comment by wackerm** [comment]
```
redis-server -v
Redis server version 2.4.14 
```

**Comment by vstakhov** [comment]
I think the lowest supported version is 2.6.12.

**Comment by wackerm** [comment]
did this change at sometime?

**Comment by vstakhov** [comment]
Yes, I have added expire set in a single command: http://redis.io/commands/set
In theory, I could use `SETEX` but 2.6.12 is already like 3 years old.

**Comment by wackerm** [comment]
well yes, but you know, debian is quite slow...

**Comment by wackerm** [comment]
i just updated to the Redis version 3.2.1 (thanks to the guys at dotdeb.org) and now it seems to work...
at least i can see `SET` commands now...

**Comment by xpunkt** [comment]
would be nice to see sqlite in rmilter for persistense database, and i think greylist expire 0 is silly to start greylistning 0 sec after first retry, expire there should be something like minimal 300 secs

i know we have fast computer like a commodore 64, but email ? :=)

**Comment by piwats** [comment]
With rmilter 1.10 (and rspamd 1.4) and redis-3.2.5 I do not see the SET commands during monitoring redis.

Currently I have 2 emails that are being greylisted for some days now.

Each time they are being delivered, I get something like this in the logs:

```
Nov 24 02:00:10 bla rmilter[21182]: <5d7edf51d3>; greylisting_check_hash: greylisted key: 'grey.aR2w3U5/MO7qmxW+FIHF1NRKTwyERLsv1ZYOpp6wpDF6817MJCcHxtCiLcRxoWLjo4oYEdB5+daFVJqFt+IN7A==': 0 seconds passed (new record), greylisted till 2016-11-24 02:05:10, expire at 2016-11-27 02:00:10, type: data hash
Nov 24 02:00:10 bla rmilter[21182]: <5d7edf51d3>; greylisting_check_hash: greylisted key: 'grey.ODGqSKElvEGUUXiRIE3koWh8oayNnzbTx+Cu4ixlSHs/aWt9bfx/yUjWUtfZ7DmdKZ1jlPIHFCQ+BqLl7eZ2CA==': 0 seconds passed (new record), greylisted till 2016-11-24 02:05:10, expire at 2016-11-27 02:00:10, type: sender, IP, recipients
```

I see rmilters GET commands in redis... but no SETs.

**Comment by piwats** [comment]
I found why it was doing so:

```
got error OOM command not allowed when used memory > 'maxmemory'
```

maxmemory in redis was too low. Fixed.
