### ISSUE TITLE
Web interface doesn't show action rewrite_subject

### ISSUE THREAD

**Issue by leoboiko** [vstakhov/rmilter#132]
Configdump:

```python
[…]
metric {
    name = "default";
    actions {
        reject = 15;
        rewrite_subject = 6;
        greylist = 3;
[…]
```

Web service:

![rspamd_screenshot_no-rewrite-subject](https://cloud.githubusercontent.com/assets/74593/16957803/4fcbab22-4db4-11e6-95d4-740a339dbb91.png)

Before changing `add_header` to `rewrite_subject`, all actions did appear in the interface.

**Comment by vstakhov** [comment]
That's rspamd issue, not rmilter one. And it is now fixed.

**Comment by leoboiko** [comment]
Sorry for misreporting, and thanks for the quick fix.
