### ISSUE TITLE
rmilter 1.9.0 crashes again #134

### ISSUE THREAD

**Issue by dehnli** [vstakhov/rmilter#136]
I got the same issue on FreeBSD/amd64 again #134
The last message in `/var/log/maillog`
`Jul 27 10:50:52 rspamd rmilter[66240]: <becf287b7d>; spamdscan: start scanning message on localhost`

**Comment by vstakhov** [comment]
Do you have it with master branch?

**Comment by dehnli** [comment]
Yes, but I'll check it again
