### ISSUE TITLE
Support DNS domain names in whitelists

### ISSUE THREAD

**Issue by leoboiko** [vstakhov/rmilter#144]
This works:

```
spamd { 
        whitelist = 127.0.0.1/32, [::1]/128, 192.168.10.10;
}
```

This gives a syntax error:

```
spamd { 
        whitelist = 127.0.0.1/32, [::1]/128, smtp.example.com;
}
```

I'd like to avoid hardcoding the smtp server's IP address…

Version: `1.9.0-1~jessie`.

**Comment by vstakhov** [comment]
Should be fixed in 1.9.2. (Use quoted strings for hostnames)
