### ISSUE TITLE
Add a way to specify an empty whitelist

### ISSUE THREAD

**Issue by leoboiko** [vstakhov/rmilter#145]
`/etc/rmilter.conf.common` has this:

```bash
spamd { 
        # whitelist - list of ips or nets that should be not checked with spamd
        # Default: empty
        whitelist = 127.0.0.1/32, 192.168.0.0/16, [::1]/128;
```

But what if I want to scan all hosts, including 127.0.0.1? I can't edit the file directly; I should add it to `rmilter.conf.common`.  However, the following all gave syntax errors:

```bash
    whitelist = ;
    whitelist = '';
    whitelist = [];
    whitelist = 0;
    whitelist = no;
    whitelist = empty;
````

I ended up adding an invalid IP address as the single whitelist entry.

**Comment by vstakhov** [comment]
Should be fixed in 1.9.2.
