### ISSUE TITLE
Add possibility to redefine variable values in debian 'init.d/rmilter' script.

### ISSUE THREAD

**Issue by rpv-tomsk** [vstakhov/rmilter#152]
I'm using `SOCKET=/var/spool/postfix/rmilter/$NAME.sock` but there is no way to change SOCKET value without `init.d/rmilter` patching.

Could you please add

```
# Include rmilter defaults if available
if [ -f /etc/default/$NAME ]; then
    . /etc/default/$NAME
fi
```

into `debian/rmilter.init` script?

Thanks.

**Comment by rpv-tomsk** [comment]
Great!

Many thanks!

**Comment by rpv-tomsk** [comment]
Great!

Many thanks!

**Comment by moisseev** [comment]
@rpv-tomsk FYI https://github.com/vstakhov/rmilter/issues/154
