### ISSUE TITLE
[feature request] antivirus limits

### ISSUE THREAD

**Issue by damned-trooper** [vstakhov/rmilter#163]
Hi.

Could you please add ability to configure message limits for clamd scan to rimlter config?
For example, if message size more than some value - do not send this message to clamd socket and bypass antivirus scan?

**Comment by andryyy** [comment]
Hi,

I am sure this should be handled with a stream size limit in ClamAV (`StreamMaxLength`). As far as I know, the file size will be given before the file will be streamed.

**Comment by damned-trooper** [comment]
Yes.
But in this case rmilter all the same will send file to scan and clamd will try to scan it genereating errors (5 times). So unnecessary workload still exist. My idea is - do not even send file to scan to avoid unnecessary workload.

**Comment by fatalbanana** [comment]
I've added this to antivirus module in rspamd 1.4: https://github.com/vstakhov/rspamd/pull/1067

**Comment by damned-trooper** [comment]
Sorry, @fatalbanana , but i have some stupid questions:
1. Antivirus integration is rmilter function. Is not it? I mean rmilter first send message to clamd, not rspamd. So your function will work AFTER message was send to clamd.
2. Where should i config `max_size` parameter?
3. `if not max_size then return end` - is this correct? Maybe `return true`?

**Comment by fatalbanana** [comment]
1) It's a question of how one wants to do it. Presumably if you configure antivirus integration in rspamd you will unconfigure it in rmilter.
2) Inside the scanner configuration block (same place as `attachments_only`): https://rspamd.com/doc/modules/antivirus.html
3) It's correct: Function returns false (or nil) in case scanning _should_ happen (ie. the message is _not_ too large).

**Comment by damned-trooper** [comment]
1. So, if i'll use antispam module in rspamd, i can exclude AV scan in rmilter?
2. Current release 1.3 and 1.4 is testing, right?

**Comment by vstakhov** [comment]
1) Rmilter exists just because I had no chance to write milter functionality in Rspamd. I obviously won't like to add any new features to Rmilter encouranging Rmilter users to use its functions within Rspamd which would simplify the final migration some day in future.

**Comment by damned-trooper** [comment]
It's good. I want migrate to rspamd AV module.
And so when to expect 1.4 release?
