### ISSUE TITLE
DKIM not working. File exists but not used.

### ISSUE THREAD

**Issue by virusmoere** [vstakhov/rmilter#165]
Error:

> Nov 22 10:40:29 inter rmilter[10418]: <5edaaf838e>; cannot find key for domain domain.de at /etc/dkim/domain.de.dkim.key
> Nov 22 10:40:29 inter rmilter[10418]: <5edaaf838e>; cannot find key for domain domain.de at /etc/dkim/domain.de.rdkim-2016.key
> Nov 22 10:40:29 inter rmilter[10418]: <5edaaf838e>; cannot add signature for domain domain.de: not found

Config:

> dkim {
>     enable = true;
>     domain {
>         key = /etc/dkim;
>         domain = "*";
>         selector = "dkim";
>     };
>     header_canon = relaxed;
>     body_canon = relaxed;
>     sign_alg = sha256;
> }

Any Ideas? Tried stable and unstable versions on the Ubuntu 16.04 Repository. Also tried the "dkim" selector and generated new keys for that. The files exist and have the correct permissions.

**Comment by fatalbanana** [comment]
The error message seems to suggest `stat()` on the file failed, does the rmilter user have permission to traverse the parent directory?

You may want to consider [using rspamd for DKIM signing](https://rspamd.com/doc/modules/dkim.html)

**Comment by virusmoere** [comment]
Thanks it works now after reowning the directory to the _rmilter user...

Why would I use rspamd for DKIM signing? Seems to be very complex in comparison to rmilter.


Thanks :-)
