### ISSUE TITLE
Greylist don't let mails pass

### ISSUE THREAD

**Issue by setiseta** [vstakhov/rmilter#173]
Hello,

I actually have trouble with greylisting in rmilter / rspamd.
in rmilter i always see:

```
<..>; msg done: queue_id: <..>; message id: <...>; ip: 123.345.789.100; from: <...>; rcpt: <my@domain.com> (1 total); user: unauthorized; spam scan: greylisted, action: greylist; virus scan: skipped, spamd greylist; dkim: skipped, spamd greylist
```
also after the greylist time is over i get this message.
rspamd is not configured to greylist, so i wonder why it writes here "spamd greylist"
greylisting should only do the rmilter part.

on Issue #175 its written to not use greylisting in rmilter.
is it broken actually? or is it issue related?

thx for help.

**Comment by vstakhov** [comment]
Short answer: do not use greylisting in Rmilter. Greylisting, dkim signing, ratelimits, replies - all these features exist merely to provide backward compatibility. Do **NOT** use them for the new setups and switch to Rspamd modules whenever you have any issues with Rmilter. Rmilter historically provided a lot of functions. However, they now have better and **supported** implementations in Rspamd. Rmilter now is intended just to provide a dialog between Rspamd and Milter enabled MTA (sendmail, postfix). Please do not use it for anything else.

**Comment by setiseta** [comment]
kk thx for the fast answer.
have a nice day

**Comment by vstakhov** [comment]
Ok, I've updated Rmilter docs to reflect this issue.
