### ISSUE TITLE
Can't override dkim selector in custom configuration file

### ISSUE THREAD

**Issue by opi** [vstakhov/rmilter#174]
Hi,
I'm using a `/etc/rmilter.conf.d/custom.conf` file, it works well for some options (like `bind_socket`), but I can't manage to override DKIM settings.

What I'm try to do:
```
dkim {
    domain {
        key = /etc/dkim;
        domain = "*";
        selector = "mail";
    };
};
```
( to use "mail" instead of "dkim" )

**Comment by vstakhov** [comment]
Don't use Rmilter dkim signing: https://rspamd.com/rmilter/#project-state

**Comment by opi** [comment]
you mean that rmilter is not needed anymore, and features like dkim signing are now handled by rspamd ? (just to be clear in my mind..)

**Comment by fatalbanana** [comment]
Rmilter is still needed to facilitate integration with rspamd; for everything else ([dkim signing](https://rspamd.com/doc/modules/dkim_signing.html), [antivirus](https://rspamd.com/doc/modules/antivirus.html), [greylisting](https://rspamd.com/doc/modules/greylisting.html), [replies](https://rspamd.com/doc/modules/replies.html), [ratelimits](https://rspamd.com/doc/modules/ratelimit.html)) you should use features of rspamd.

**Comment by opi** [comment]
OK. this setup seems to be more complicated to me, but I'll try to implement it properly !
Thanks for your quick anwers
