### ISSUE TITLE
Virus scan: skipped, no av servers; in logs

### ISSUE THREAD

**Issue by madorin** [vstakhov/rmilter#178]
Please add a setting enabled for clamav section to have a way to disable it.

**Comment by xpunkt** [comment]
Comment servers in clamav sektion disable it, enable will be more servers defined in a single servers line

But yes it will be more consistence with enable=true or false

**Comment by madorin** [comment]
I even don't have clamav section in my rmilter, but some defaults are defined in rmilter.conf.common

**Comment by 4nd3r** [comment]
it's rmilter, not rspamd: https://rspamd.com/rmilter/

tldr use antivirus module in rspamd and rmilter for communication between mta and rspamd
