### ISSUE TITLE
Missing from Trusty apt repos

### ISSUE THREAD

**Issue by lobsterdore** [vstakhov/rmilter#185]
It seems that the rmilter package no longer exists in the Trusty 64 apt repos, I've also added the rspamd repository (not sure if it's supposed to exist in there). When installing via apt-get the package is shown as missing:

```BASH
apt-get install rmilter
"No package matching 'rmilter' is available
```

**Comment by vstakhov** [comment]
Rmilter is no longer supported. Do not use it.

**Comment by lobsterdore** [comment]
OK that answers that one then, thanks.
