### ISSUE TITLE
config file parse error

### ISSUE THREAD

**Issue by MartinNowak** [vstakhov/rmilter#21]
No matter what version of rmilter or what config I try, I always get config file parse errors.
Using the master branch and `./rmilter -c rmilter.conf.sample` I get this.

```sh
config file parse error! line: 20, text: clam1.example.com, reason: yyparse: add_clamav_server
```

I'm running a fedora system if that matters.

**Comment by wackerm** [comment]
With the latest update to stable (rmilter 1.7.1-1~wheezy) i got a similar error today:

    rmilter -c /etc/rmilter.conf
    config file parse error! line: 21, text: /var/run/clamav/clamd.ctl, reason: yyparse: add_clamav_server

I'm running Debian Wheezy and using an unix clamav-socket. I was using the previous rmilter version (1.6.7-1~wheezy) with the same config file without this error...

**Comment by sativouf** [comment]
Same here with the latest update to stable in jessie (1.7.1-1~jessie), downgrading from the cutting edge "experimental" repo, where it was working just fine on that part.

**Comment by vstakhov** [comment]
This issue should be fixed now. Experimental packages include this fix.

**Comment by wackerm** [comment]
unix clamav-socket works now! thanks for the fix!
