### ISSUE TITLE
[help needed] dkim does not sign

### ISSUE THREAD

**Issue by wildstray** [vstakhov/rmilter#26]
I think it is not an issue, but I need help to configure. I wish to use rmilter to replace (also) opendkim, so I read documentation and manual and configured dkim as follows:

dkim {
    domain {
                key = /etc/mail/mydomain.it.key;
                domain = "mydomain.it";
                selector = "check";
        };
    header_canon = simple;
    body_canon = simple;
    sign_alg = sha256;
    auth_only = no;
};

rmilter is compiled with dkim support (debian package) but never add signature to emails from "mydomain.it" and nothing about dkim is logged.

working opendkim configuration:

Domain                  mydomain.it
KeyFile                 /etc/mail/mydomain.it.key
Selector                check
Mode                    sv

**Comment by wildstray** [comment]
PS: I didn't fully understand the auth_only flag...

**Comment by vstakhov** [comment]
Is your rmilter built with DKIM support?

**Comment by wildstray** [comment]
Mystery solved XD It's an issue of the Debian package! In debian/rules:
-DENABLE_SPF=ON -DENABLE_DKIM=ON -DMANDIR=/usr/share/man
have to be:
-DWITH_SPF=ON -DWITH_DKIM=ON -DMANDIR=/usr/share/man
Anyway, there is a minor issue with include dkim.h in include/rmilter.h and include/cfg_file.h:
#ifdef WITH_DKIM
#include <dkim.h>  ---> <opendkim/dkim.h> to compile
#endif
...now I'm triying to understand why libopendkim and libspf2 are not linked so gcc returns a lot of undefined reference...

**Comment by wildstray** [comment]
Also CMakeLists.txt has to be patched. Now compiles. But messages are never signed :(

**Comment by vstakhov** [comment]
That's not true, `-DENABLE_SPF=ON -DENABLE_DKIM=ON` are correct settings, I'm sorry for confusion. I'm not pretty sure about auth_only setting. In my setup, I set DKIM signatures merely for authenticated users and have the following settings in my Postfix main.conf: 
~~~
smtpd_milters = inet:localhost:9900
milter_default_action = accept
milter_protocol = 6
milter_mail_macros = i {mail_addr} {client_addr} {client_name} {auth_authen}
~~~

My rmilter.conf DKIM section uses wildcard domains:

~~~
dkim {
    domain {
                key = /etc/dkim;
                domain = "*";
                selector = "dkim";
        };
    header_canon = relaxed;
    body_canon = relaxed;
    sign_alg = sha256;
};
~~~

And the key is named as following: `/etc/dkim/highsecure.ru.dkim.key`

**Comment by wildstray** [comment]
Updated to the same configuration. Still no way... then, strace unveilled me that the key could not be read due to permissions. With a chgrp i solved, but I think a more verbose logging (eg a warning for EACCES on the key file) might be added.

**Comment by vstakhov** [comment]
Yes, logging would be good. But currently, rmilter is somehow unmaintained project. I plan to make a complete rework of it some day.

**Comment by rrelmy** [comment]
I tried to use the rsa-sha256 signature algorithm, the config was not valid.
In the code I find no reference for rsa-sha256 only in the documentation, has rsa-sha256 been implemented?

    Aug 12 00:51:46 mail rmilter[20241]: main: starting rmilter version 1.6.1
    Aug 12 00:51:46 mail rmilter[20241]: config file parse error! line: 275, text: rsa-sha256, reason: syntax error
    Aug 12 00:51:46 mail rmilter[20241]: yyparse: cannot parse config file, 1 errors

**Comment by vstakhov** [comment]
It's just `sha256` since `RSA` is the only supported signature system for now.
