### ISSUE TITLE
spam_header = true; causes config file error

### ISSUE THREAD

**Issue by sbrl** [vstakhov/rmilter#35]
Hello,
I have just tried adding the following lines to the `spamd {  }` section of my config file:

```
spam_header = true;
extended_spam_headers = true;
```

But I get these errors:

```
Aug 17 10:12:19 starbeamrainbowlabs rmilter[16439]: config file parse error! line: 96, text: true, reason: syntax error
Aug 17 10:13:30 starbeamrainbowlabs postfix/smtpd[16440]: warning: connect to Milter service inet:127.0.0.1:11444: Connection refused
```

Since the default value was false, I thought that setting it to `true` would work as expected, but it doesn't. What's the correct syntax please?

**Comment by moisseev** [comment]
`extended_spam_headers = yes;`
works for me.

**Comment by sbrl** [comment]
@moisseev Yep, thanks! It works for me too. It doesn't appear to work with the `spam_header` directive though...
