### ISSUE TITLE
whitelist rcpt error 

### ISSUE THREAD

**Issue by mnik247** [vstakhov/rmilter#47]
Whitelist: global recipients whitelist
If whitelist rcpt email contain any digits (minimum 1) - rmilter can't start - error config.
#config file parse error! line: 22, text: user1, reason: syntax error

It's was error 1.6.4 and present 1.6.5 too.
maillog:
Nov 12 22:48:17 vb rmilter[20992]: main: starting rmilter version 1.6.5
Nov 12 22:48:17 vb rmilter[20992]: config file parse error! line: 20, text: user1, reason: syntax error
Nov 12 22:48:17 vb rmilter[20992]: yyparse: cannot parse config file, 1 errors

**Comment by mnik247** [comment]
Is it possible to fix this error?
Rmilter can't start if global whitelist contain rcpt with digits.

**Comment by vstakhov** [comment]
The best way is to kill this bloody project and implement its functionality in rspamd... But I'll try to write a workaround for now.

**Comment by vstakhov** [comment]
Should work in master by using double quotes for whitelist elements.

**Comment by mnik247** [comment]
Updated to 1.6.6 and tested global whitelist. 
Work using double quotes with one rcpt only.
whitelist = "user0@exmaple.com"; -> whitelist work
whitelist = "user0@exmaple.com", "user1@exmaple.com";  - whitelist not work
whitelist = "user0@exmaple.com, user1@exmaple.com";   - whitelist not work
No errors, but whitelist not worked.

**Comment by mnik247** [comment]
Builed rpm 1.6.7 for CentOS 6  and check again:
Result same as for version 1.6.6:
whitelist = "user0@exmaple.com"; -> whitelist work
whitelist = "user0@exmaple.com", "user1@exmaple.com"; - whitelist not work
whitelist = "user0@exmaple.com, user1@exmaple.com"; - whitelist not work
No errors, but whitelist with more one rcpt not worked.
Can you help me?

**Comment by vstakhov** [comment]
I have reordered yacc rules... Does it work with the following cases:

- "user1@domain", "user2@domain"
- "user1@domain", user@domain
- user@domain, another_user@domain

**Comment by mnik247** [comment]
Rebuild rmilter 1.6.7
with updated cfg_file.y to:
whitelist_list:
        STRING {
                add_rcpt_whitelist (cfg, $1, 1);
        }
        | QUOTEDSTRING {
                add_rcpt_whitelist (cfg, $1, 1);
        }
        | whitelist_list COMMA STRING {
                add_rcpt_whitelist (cfg, $3, 1);
        }
        | whitelist_list COMMA QUOTEDSTRING {
                add_rcpt_whitelist (cfg, $3, 1);
        }
        ;
Result:
whitelist = postmaster@localhost, root@localhost; #work
whitelist = "postmaster@localhost","root@localhost"; #not work
whitelist = "postmaster@localhost, root@localhost"; #not work
whitelist = "root@localhost"; # not work
whitelist = root@localhost; #work

**Comment by vstakhov** [comment]
I've applied the greediness fix patch to the sources. Could you test it as well?

**Comment by mnik247** [comment]
After last patch https://github.com/vstakhov/rmilter/commit/d929983406f569cdce7bf82c1b8cc78f7c788da3 whitelist working.
#testing 03.12.2015 - 1.6.7-4
#whitelist = postmaster@localhost, root@localhost; #work
#whitelist = "postmaster@localhost","root@localhost"; #work
#whitelist = postmaster@localhost, "root@localhost"; #work
#whitelist = "root@localhost"; #work
#whitelist = root@localhost;    #work

Thanks.
