### ISSUE TITLE
rmilter-1.6.5 hangs on amd64

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rmilter#48]
I've upgraded mail/rmilter FreeBSD port 1.6.1_1 -> 1.6.5 on two systems that have similar configurations but different hardware platforms.

1.6.1_1 works well on both platforms. 1.6.5 works on i386, but hangs on amd64. I didn't find any substantial difference in the configurations.

Rmilter creates temporary files in `tempdir` but doesn't write anything to the log and doesn't answer to postfix.
```
Nov 14 12:06:15 mx postfix/cleanup[52506]: warning: milter unix:/var/run/rmilter/rmilter.sock: can't read SMFIC_BODYEOB reply packet header: Operation timed out
Nov 14 12:06:19 mx postfix/submission/smtpd[54937]: warning: milter unix:/var/run/rmilter/rmilter.sock: can't read SMFIC_DATA reply packet header: Operation timed out
Nov 14 12:09:20 mx postfix/cleanup[52527]: warning: milter unix:/var/run/rmilter/rmilter.sock: can't read SMFIC_BODYEOB reply packet header: Operation timed out
Nov 14 12:12:25 mx postfix/cleanup[52506]: warning: milter unix:/var/run/rmilter/rmilter.sock: can't read SMFIC_BODYEOB reply packet header: Operation timed out
```
I can't kill rmilter process with -TERM, -KILL works.

```
# uname -mrsv
FreeBSD 10.2-RELEASE FreeBSD 10.2-RELEASE #0 r286666: Wed Aug 12 19:31:38 UTC 2015     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  i386
```
```
# uname -mrsv
FreeBSD 10.2-RELEASE FreeBSD 10.2-RELEASE #0 r286666: Wed Aug 12 15:26:37 UTC 2015     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
```

**Comment by vstakhov** [comment]
Any chances to get `ktrace` of the hanging process?

**Comment by moisseev** [comment]
I've sent ktrace output by email.
What `rmilter -n` does? I couldn't find `-n` option in man rmilter(8).

**Comment by moisseev** [comment]
I forgot to mention the issue doesn't occur if TCP socket is used.

**Comment by vstakhov** [comment]
I cannot reproduce your issue with the current master and I haven't received your trace. `-n` option is described in `rmilter --help`.

**Comment by moisseev** [comment]
`rmilter -n` works, but it can't be used in production. I've sent trace to your mail box at highsecure.ru once more.

**Comment by vstakhov** [comment]
I can't see anything bad in the trace. The only difference of `-n` mode is not calling of `daemon` function.

**Comment by moisseev** [comment]
I tried different environment and combination of options. Rmilter without `-n` hangs always, but with `-n` it always works. More over, with `-n` it can work daemonized too. I've added `-n` option rmilter arguments in rc script and and rmilter works!
~~~diff
--- /usr/local/etc/rc.d/rmilter.sh.orig 2015-11-17 20:49:47.468094000 +0300
+++ /usr/local/etc/rc.d/rmilter.sh      2015-11-17 20:55:37.043580000 +0300
@@ -32,6 +32,6 @@
 sig_reload="USR1"

 command="/usr/sbin/daemon"
-command_args="-p $rmilter_pidfile $procname -c /usr/local/etc/rmilter.conf"
+command_args="-p $rmilter_pidfile $procname -n -c /usr/local/etc/rmilter.conf"

 run_rc_command "$1"
~~~

**Comment by vstakhov** [comment]
Oh, in FreeBSD it runs using `daemon` routine. Maybe there is some problem with that?

**Comment by kAworu** [comment]
I experience the same issue with rmilter-1.6.6. The workaround using TCP socket works, launching rmilter with -n works too.

**Comment by kAworu** [comment]
@moisseev can you test with this patch against 1.6.6 to confirm that it fix your issue ? https://gist.github.com/kAworu/15278e6886f6f53672ab

**Comment by moisseev** [comment]
Sorry for delay. I had no chance to test the patch by @kAworu sooner.
The patch fixes the issue on amd64, but brings it to i386. I've installed rmilter from master (b25f5df) and it hangs on i386 now.

**Comment by moisseev** [comment]
Please ignore my previous comment. It seems I messed up something during installation.
Actually 1.6.6 breaks rmilter on i386, the patch fixes it.
