### ISSUE TITLE
rmilter-1.6.6 - rpm build error on Centos 6.

### ISSUE THREAD

**Issue by mnik247** [vstakhov/rmilter#49]
Last rpm (rmilter 1.6.6) for Centos 6 not published yet, and I try to build rpm.
And I can't build rpm from source:
/root/rpmbuild/BUILD/rmilter-1.6.6/src/beanstalk.c:483: warning: ignoring return value of 'write', declared with attribute warn_unused_result
[ 57%] Building C object CMakeFiles/rmilter.dir/src/main.c.o
/root/rpmbuild/BUILD/rmilter-1.6.6/src/main.c: In function 'main':
/root/rpmbuild/BUILD/rmilter-1.6.6/src/main.c:286: error: 'true' undeclared (first use in this function)
/root/rpmbuild/BUILD/rmilter-1.6.6/src/main.c:286: error: (Each undeclared identifier is reported only once
/root/rpmbuild/BUILD/rmilter-1.6.6/src/main.c:286: error: for each function it appears in.)
make[2]: *** [CMakeFiles/rmilter.dir/src/main.c.o] Error 1
make[1]: *** [CMakeFiles/rmilter.dir/all] Error 2
make: *** [all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.fwXKnF (%build)

But building v.1.6.5 is success.

**Comment by vstakhov** [comment]
I've fixed this issue locally and built rpm packages for 1.6.6

**Comment by mnik247** [comment]
Thanks.
I updated rmilter from repo.
