### ISSUE TITLE
Rmilter doesn't create pid file by default.

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rmilter#54]
After some changes in between 1.6.5. and 1.6.6 rmilter doesn't create pid file at all if path to pid file isn't set in `rmilter.conf`.
Rmilter skips pid file creation instead of using the default path as described in rmilter.conf comment:
```
# pidfile - path to pid file
# Default: pidfile = /var/run/rmilter.pid
```

**Comment by fatalbanana** [comment]
I understand that it's intentional. Pid file is not required if running under Systemd for example. Probably docs should be updated to indicate that default is unset.

**Comment by xpunkt** [comment]
/var/run is in tmpfs ?, if rmilter is not started as root it cant create file here, so package managers must change init scripts to make /var/run/rmilter dir before create pid file, if rmilter is started as root and drops priveleges it cant unlink on stop, i dont know how current rmilter is handling this, but

**Comment by denji** [comment]
vstakhov/rmilter@f20b1f4ddae23a0b1c22f377aff94024db38b64f
vstakhov/rmilter@47a90c8a857b3af4ad8430a67adef49b5e089dbc
