### ISSUE TITLE
Invalid DKIM signatures

### ISSUE THREAD

**Issue by skibbipl** [vstakhov/rmilter#57]
I think latest rmilter generates invalid DKIM signatures:
`DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=example.com; s=fd:3; t=1448366114; bh=awa4U9AyyvLFEE5aXGUtGmK+gOMMzL8CfGyRVWP1ulg=; h=Mime-Version:Date:Content-Type:Message-ID:From:Subject:To; b=v505kNLPyNdefN92LZw4ROq6DA6iBe4JCta9W4md8gGkwqxMfqvcSUNzplxqo11IkTd7Ageini/U3O9xN4cWxhkDHfUU7HjYofA0Ircv+ZkGDpVhd4fkRKuQ8vrXDIpplfq79kpXdNyT1EAfZyj25MEU7FTPWLs7qazlYgCwlsA=`
Is seems selector part is broken: `s=fd:3`
My rmilter config:
```
        domain {
                key = /etc/dkim/example.com.dkim2016.key;
                domain = "example.com";
                selector = "dkim2016";
        };
        header_canon = relaxed;
        body_canon = relaxed;
        sign_alg = sha256;
```

**Comment by vixns** [comment]
Related issue here using nightly jessie package, with wildcard domain, mails are not signed
strace shows it's using "rmilter" as selector, not the selector provided in the config file ("default").
Renaming the keyfile to ${domain}.rmilter.key allows mails to be signed with the "rmilter" selector.
Don't know yet if it produce a valid signature

**Comment by skibbipl** [comment]
Selector issue is fixed, however @vixns issue is still there. I'll keep this ticket open.

**Comment by vstakhov** [comment]
Which issue is still here? I don't understand.

**Comment by skibbipl** [comment]
Wildcard selector is not signing mails at all.
```
domain {
key = /etc/dkim;
domain = "*";
selector = "dkim";
};
```

**Comment by vstakhov** [comment]
@vixns describes another issue: wildcard signing works but it does not use the correct selector. To my sense, this issue is directly related to the issue you've reported and it should be fixed now.

**Comment by skibbipl** [comment]
Yes, my fault. After cleaning up old rmilter processes and fixing permission issues I got it working.
Thanks for the quick fix!

**Comment by vixns** [comment]
> Le 24 nov. 2015 à 19:10, Vsevolod Stakhov <notifications@github.com> a écrit :
> 
> @vixns describes another issue: wildcard signing works but it does not use the correct selector. To my sense, this issue is directly related to the issue you've reported and it should be fixed now.

fixed, thx !
