### ISSUE TITLE
clamav can't scan mails due permission errors

### ISSUE THREAD

**Issue by skibbipl** [vstakhov/rmilter#58]
Hello,
I'm trying to configure rmilter to scan mails with clamav. Unfortunately I'm getting following errors:
```
rmilter[12793]: clamav: error (/var/run/clamav/clamd.ctl) /tmp/msg.XXa23DuY: Access denied.
rmilter[12793]: clamscan: retry limit exceeded, /var/run/clamav/clamd.ctl, /tmp/msg.XXa23DuY
```
It seems that those temp messages are created with following permissions:
`-rw------- 1 _rmilter _rmilter    0 lis 26 11:47 msg.XXa23DuY`
therefore clamav cannot read them. Can rmilter create temp messages with different permissions? As a workaround I started clamav daemon as _rmilter user, but I think is not an optimal solution.

**Comment by bax-** [comment]
Same problem here.
Is there a way around changing the user?
I'll stick to clamav-milter for now…

**Comment by vstakhov** [comment]
I'll check that tonight. I would likely allow to specify custom permissions on temp files generated by rmilter.

**Comment by denji** [comment]
```
# sudo adduser _rmilter postfix
Adding user `_rmilter' to group `postfix' ...
Adding user _rmilter to group postfix
Done.
# sudo adduser _rmilter clamav

```

**Comment by vstakhov** [comment]
But that won't fix an issue counting that temp files are created with 0600 permissions.

**Comment by vstakhov** [comment]
Well, I removed `umask` call and added `tempfiles_mode` global argument that would set the desired mode for files created by rmilter. Anything else is up to you and your setup.

**Comment by skibbipl** [comment]
Thanks, but I'm little bit confused - I don't see any new setting in rmilter config to set `tempfiles_mode`. I tried to add `temfiles_mode = 00666` to `rmilter.conf.common` but with no luck. Clamav still cannot access temp files.

**Comment by skibbipl** [comment]
Thanks - changing `tempfiles_mode` to `00666` fixed the access denied issues.

**Comment by vstakhov** [comment]
BTW, beware of such a mode. Maybe something like 0644 is better even for the case of separated VM...

**Comment by bax-** [comment]
Any news here?
Is this option now available in the config? (it's not documented)
Or is there another way to connect to clamp without changing the clamd-user?

**Comment by skibbipl** [comment]
It's already implemented. Just put `tempfiles_mode = 00644;` in `/etc/rmilter.conf.common`.

**Comment by xpunkt** [comment]
https://github.com/vrtadmin/clamav-devel/blob/master/etc/clamd.conf.sample#L199

make sure rmilter runs in a group clamd can read on, clamd does not need to write

**Comment by alexschomb** [comment]
@xpunkt Thanks for pointing this out. Unfortunately it doesn't work.

``tempfiles_mode = 00644;`` works with clamav under latest FreeBSD. ``00640`` gives ``Permission denied`` no matter if ``AllowSupplementaryGroups`` is set to ``no`` or ``yes``.

**Comment by xpunkt** [comment]
clamd only need read access, not write access on files that are created by rmilter, so make sure clamav is in rmilter used group, i have not tested it under freebsd yet, 

check what id clamav, or id _rmilter gives as results, mode 0644 should not be needed when it works

**Comment by alexschomb** [comment]
I think I found the reason why it doesn't work. The tempfiles are owned by ''_rmilter:wheel'', but the group should be ''mail'' according to the rc.d file. I added ''_rmilter'' to this group and restarted the service, but that didn't help either. I think I'm going to solve that eventually and report back here. Thanks for your help!
