### ISSUE TITLE
DKIM selector not set correctly

### ISSUE THREAD

**Issue by falstaff84** [vstakhov/rmilter#60]
I am using rspamd and rmilter (1.6.6) on a Ubuntu Trusty installation. I enabled DKIM by using a explicit key file and specify only one domain.

The emails get signed, however the s= (selector) seems to be off. I had different values, depending on the order of the configuration file properties. Once I got the key path (!?), right now I get "s=/tmp"... 

This is my configuration:

    dkim {
        domain {
          key = /etc/dkim/domain.com.dkim.key;
          domain = "domain.com";
          selector = "dkim";
        };
        header_canon = relaxed;
        body_canon = relaxed;
        sign_alg = sha256;
    };

I also tried with domain = "*" and only the directory as key path, however in that case the emails do not get signed at all...

**Comment by fatalbanana** [comment]
Should be fixed in master: see #57

**Comment by falstaff84** [comment]
True, tried today's nightly build for Ubuntu Trusty, works like a charm with both modes of specifying the key!
