### ISSUE TITLE
Using IPv6 addresses in whitelist

### ISSUE THREAD

**Issue by falstaff84** [vstakhov/rmilter#62]
My goal is to whilelist a IPv6 address in the spamd section. I tried with and without square brackets, CIDR and address only, however rmilter seems not to be able to parse it:

    Dec  5 20:59:11 liskamm rmilter[2888]: config file parse error! line: 50, text: 2001, reason: syntax error
    Dec  5 20:59:11 liskamm rmilter[2888]: yyparse: cannot parse config file, 1 errors

I guess it is not supported (yet)?

**Comment by vstakhov** [comment]
That's not possible. I'd recommend using of whitelists in rspamd where IPv6 is fully supported.

**Comment by vstakhov** [comment]
Done :)

**Comment by falstaff84** [comment]
Cool, thx! Will going to test it once the next release is available...
