### ISSUE TITLE
Feature Request: DMARC

### ISSUE THREAD

**Issue by bax-** [vstakhov/rmilter#64]
It would be great if rmilter would also support DMARC

**Comment by vstakhov** [comment]
It won't be done. Rmilter is actually not actively supported and I don't want to continue it's development. One idea was to convert it to [librmilter](https://github.com/vstakhov/librmilter) and to include into rspamd project. But I don't see if anybody is interested in this project.

**Comment by bax-** [comment]
So Reiter won't be developed any further?
What will then be the ideal way to include rspamd with postfix?

**Comment by denji** [comment]
DMARC/SDID/ADSP/DKIM (RFC4871)
* https://github.com/halonsecurity/libdkimpp (However he is not suitable, because it uses C++)

**Comment by bax-** [comment]
Thanks!
but rspamd should still be connected using rmilter?

**Comment by vstakhov** [comment]
There is DMARC and DKIM checks support in rspamd. Why do you want that in rmilter? The only reason why there is dkim support in rmilter is actually the feature of signing messages from authorized users. I was asked for this feature just because we didn't want to have multiple milters in my previous job. But it was never ever intended for checks. And there will be no DMARC as everything now lives in rspamd (I'll disable libspf2 in rmilter soon as well).

**Comment by bax-** [comment]
Yes, I was thinking about signing and adding 'Authentication-Results:' headers.
I was also liking the idea of having only one filter, but then I'll stick to dkim, dmarc, clamav and rmilter together.

**Comment by mustafirus** [comment]
Your desire to integrate all in one violates unix philosophy - Do One Thing and Do It Well
I think for now you have 2 great products rspamd as context spam filter and rmilter as integrator of different packages in one chain.
What advantages do you plan to get by integrating all in rpamd? 
performance? usability(simple configuration)? advanced features(ex. scripting of results of noncontext checks)?

**Comment by vstakhov** [comment]
Man, I'm not a philosopher, I'm the developer. All content and policies check are intended to run in rspamd. Rmilter is indeed just a shim between MTA and different scanners and services.

**Comment by danielcb** [comment]
Is there another way to connect rspamd to postfix than? Or will postfix just not be supported by rspamd?

**Comment by vstakhov** [comment]
I don't quite understand what do you mean. Rmilter is the intended shim to connect rspamd with postfix and sendmail MTA.

**Comment by danielcb** [comment]
If you're not planning to maintain rmilter any further, will support for postfix be dropped or will there by another milter/another way to connect rspamd to postfix?

**Comment by vstakhov** [comment]
Ok, my comment seems to be too confusing. In fact, I continue support for rmilter and have no plans to stop it. However, I do not want to re-implement rspamd features in rmilter: it's just meaningless.
