### ISSUE TITLE
Check DKIM on incoming mail / add header

### ISSUE THREAD

**Issue by bax-** [vstakhov/rmilter#65]
rmilter doesn't add a `Authentication-Results:` like openDKIM does.
It would be great if there was the possibility to add one and to support logging of these checks.
##

**Comment by vstakhov** [comment]
Maybe, that could be done using rspamd. In fact, rmilter still uses legacy protocol to communicate with rspamd and it lacks many features. But I have no resources to do the necessary refactoring.

**Comment by bax-** [comment]
would be a nice addition!

**Comment by Antwan86** [comment]
What's the point of having DKIM support if it doesn't return the results ?

**Comment by vstakhov** [comment]
Rmilter uses DKIM just for signing. That's the point - DKIM checks are done in rspamd and this ticket suggests to pass information about DKIM from rspamd to rmilter (though, I'm not sure if that has any useful meaning).
