### ISSUE TITLE
Redis support

### ISSUE THREAD

**Issue by bax-** [vstakhov/rmilter#68]
Support for Redis would be appreciated.
Or is there any way to use Redis with the current version?

**Comment by vstakhov** [comment]
https://gist.github.com/vstakhov/7627f356d38e56c5155a

**Comment by bax-** [comment]
@vstakhov thanks.
But what configuration would I have to add if I wanted to use my Redis server?
And which functions of rmilter (aside from SPF) are already being done by Rspamd?
Sorry if my questions sound stupid but the documentations on Github and on rspamd.com seem to differ and the Rspamd version in FreeBSD ports also doesn't seem to be up to date which adds to some confusion on my side…
