### ISSUE TITLE
memcached errors

### ISSUE THREAD

**Issue by vixns** [vstakhov/rmilter#70]
milter is configured to work with legacy memcached cache, please consider switching to redis by adding 'use_redis = true;' into configuration
main: starting rmilter version 1.7.0, listen on inet:11339@127.0.0.1
reload_thread: starting...
memc_log(164): host: 127.0.0.1, port: 52011
memc_read: user's buffer is too small: 16, 0 required
memc_log(164): host: 127.0.0.1, port: 52011
memc_read: user's buffer is too small: 16, 0 required

rmilter: /rmilter-1.7.0/src/cache.c:143: rmilter_query_cache: Assertion `datalen != ((void *)0) && *datalen != 0' failed.

**Comment by vstakhov** [comment]
Do you have the core file for this assert? Backtrace would help I suppose.

**Comment by vixns** [comment]
It was on a production node, i've switched to redis and cannot rollback now.

**Comment by vstakhov** [comment]
I see, I'll try to hunt it but redis is the better choice indeed.

**Comment by vixns** [comment]
If that helps, I also had same issue as #71, but It no longer append since i'm using redis.

**Comment by vstakhov** [comment]
It seems I've found the issue in the memcached code
