### ISSUE TITLE
rspamd headers and outgoing emails

### ISSUE THREAD

**Issue by mnik247** [vstakhov/rmilter#76]
Is it possible to add  "extended_spam_headers" and "spam_header" only for incoming emails and not add to outgoing?

**Comment by vstakhov** [comment]
So how'd you distinguish between 'incoming' and 'outcoming'? I think I need to add the option like `our_networks` which would act like SMTP auth enabling DKIM and disabling certain checks or adding extended headers.

**Comment by damned-trooper** [comment]
If you use postfix, you can create 2 instance (see postfix multiinstance manual). In this case only one instance (incoming) will work with rmilter and no spam headers will add to outgoing messages.

**Comment by mnik247** [comment]
@vstakhov 
I think optiion "our_domains" can help to detect 'incoming' and 'outgoing' emails.
Or other way to skip adding extended headers.

@damned-trooper 
Thanks. I use postfix(Zimbra) and will see "postfix multiinstance manual"
@damned-trooper

**Comment by vstakhov** [comment]
I've added `our_networks` option, mail for these IP networks should be treated as mail from authenticated users. So it won't be checked if `strict_auth` is `yes`.
