### ISSUE TITLE
Problems with clamd

### ISSUE THREAD

**Issue by damned-trooper** [vstakhov/rmilter#77]
With last build of rmilter (from git) i got problems with clamd scan.
As i can see, rmilter does not try to use clamav.

Config:
>clamav {
>        servers = localhost:3310;
>        connect_timeout = 2s;
>        port_timeout = 6s;
>        results_timeout = 20s;
>        error_time = 10;
>        dead_time = 300;
>        maxerrors = 10;
>};

There are no error messages, but there are no any messages about scan.
In clamd i start debug mode and when i connect to daemons socket via telnet i've got messages like this in logs:
>Jan 29 20:13:08 mx01 clamd: $Got new connection, FD 11
>Jan 29 20:13:08 mx01 clamd: $Received POLLIN|POLLHUP on fd 7
>Jan 29 20:13:08 mx01 clamd: $fds_poll_recv: timeout after 10 seconds
>Jan 29 20:13:12 mx01 clamd: $Received POLLIN|POLLHUP on fd 11
>Jan 29 20:13:12 mx01 clamd: $got command VERSION (8, 8), argument:
>Jan 29 20:13:12 mx01 clamd: $Receive thread: closing conn (FD 11), group finished
But there are no messages about connect from rmilter.

I try to run tcpdump. I captured traffic I can see my telnet connections, but i could no see any packets from rmilter.

Is there a way to debug rmilter to understand what happens?
P.S. When i try to use file socket nothing changes.

**Comment by vstakhov** [comment]
Is there anything useful in rmilter logs?

**Comment by damned-trooper** [comment]
No.
Typical session in maillog for rmilter:
>Jan 29 20:21:50 mx01 rmilter[52282]: mlfi_eom: D63F3153A7: tempfile=/tmp/msg.XX7nbLKZ, size=1211
>Jan 29 20:21:52 mx01 rmilter[52282]: spamdscan: scan qid: <D63F3153A7>, mid: <undef>, 2.004810, 127.0.0.1, metric: default: [-6.490000 / 15.000000], symbols: ONCE_RECEIVED(1.00), CUSTOM_IP_WHITELIST(-10.00), R_SPF_ALLOW(-1.00), MISSING_MID(3.00), HFILTER_HELO_5(3.00), MISSING_MIMEOLE(1.50), BAYES_HAM(-3.99)
>Jan 29 20:23:22 mx01 rmilter[52282]: mlfi_eom: AF76D153A7: tempfile=/tmp/msg.XXncHypR, size=111196
>Jan 29 20:23:23 mx01 rmilter[52282]: spamdscan: scan qid: <AF76D153A7>, mid: <827831856CB827A4787D323C385AE996@softlinedirect.ru>, 0.383498, 127.0.0.1, metric: default: [6.940000 / 15.000000], symbols: R_SPF_ALLOW(-1.00), R_SUSPICIOUS_URL(6.00), URIBL_BLOCKED(0.00), R_DKIM_ALLOW(-1.00), R_PARTS_DIFFER(2.94)
>Jan 29 20:23:23 mx01 rmilter[52282]: awl_add: insert ip 93.91.160.210 in cache, insert first item

And in the clamd log file only my old attempt to test via telnet:
>Jan 29 20:17:18 mx01 clamd: $Received POLLIN|POLLHUP on fd 11
>Jan 29 20:17:18 mx01 clamd: $got command VERSION (8, 8), argument:
>Jan 29 20:17:18 mx01 clamd: $Receive thread: closing conn (FD 11), group finished
>Jan 29 20:17:18 mx01 clamd: $Consumed entire command
>Jan 29 20:17:18 mx01 clamd: $Number of file descriptors polled: 1 fds
>Jan 29 20:17:18 mx01 clamd: $fds_poll_recv: timeout after 600 seconds

**Comment by vstakhov** [comment]
What if you specify clamav server as IP address?

**Comment by damned-trooper** [comment]
I've tried set 127.0.0.1:3310. No effect.
If i set ::1:3310 (clamd listen both v4 and v6) rmilter could not parse config file.
If i use file socket of clamd - nothing changes.

**Comment by damned-trooper** [comment]
I get old logs (17 Jan) and i can see, that there was an additional line for scan:

>Jan 17 02:54:09 mx01 rmilter[10960]: mlfi_eom: E10AF2E169: tempfile=/tmp/msg.XXVVZ4se, size=563
>Jan 17 02:54:10 mx01 rmilter[10960]: spamdscan: scan qid: <E10AF2E169>, mid: <undef>, 0.455503, 127.0.0.1, metric: default: [-1.000000 / 15.000000], symbols: MIME_HTML_ONLY(3.00), MISSING_MID(3.00), ONCE_RECEIVED(1.00), HFILTER_HELO_5(3.00), R_SPF_ALLOW(-1.00), CUSTOM_IP_WHITELIST(-10.00)
>**Jan 17 02:54:10 mx01 rmilter[10960]: clamscan: scan 0.002087, (null), /tmp/msg.XXVVZ4se**

Now there are no clamscan events in log files. Last message - Jan 19 19:50:32 (at this period i updated rmilter).

**Comment by damned-trooper** [comment]
it's look like in rmilter.c in code:
>	if (cfg->clamav_servers_num != 0 && !ip_whitelisted) {
>		msg_debug ("mlfi_eom: %s: check clamav", priv->mlfi_id);
>		r = check_clamscan (priv->file, strres, sizeof (strres));
>		if (r < 0) {
>			msg_warn ("mlfi_eom: %s: check_clamscan() failed, %d", priv->mlfi_id, r);
>			CFG_UNLOCK();
>			mlfi_cleanup (ctx, false);
>			return SMFIS_TEMPFAIL;
>		}
>		if (*strres) {
>			msg_warn ("mlfi_eom: %s: rejecting virus %s", priv->mlfi_id, strres);
>			snprintf (buf, sizeof (buf), "Infected: %s", strres);
>			smfi_setreply (ctx, RCODE_REJECT, XCODE_REJECT, buf);
>			CFG_UNLOCK();
>			mlfi_cleanup (ctx, false);
>			return SMFIS_REJECT;
>		}
condition is always false...

**Comment by vstakhov** [comment]
You are right, this commit should likely fix the issue. I'll start experimental packages rebuilt soon.

**Comment by damned-trooper** [comment]
I build new version. rmilter now connect to clamd, but there is some one bug.
It's look like rmilter now incorrect works with responces of clamd.
For example:
>Fri Jan 29 21:57:50 2016 -> stream(127.0.0.1@1592): Block.EXE-zip.UNOFFICIAL(cec4ee487e4770cdee46ca252ffe4f3e:366517) FOUND
(This is clamd.log. Clamd FOUND virus) 
But rmilter return "4.7.1 Service unavailable":
>Jan 29 21:57:50 mx01 postfix-in/cleanup[53691]: F0FA41A459: milter-reject: END-OF-MESSAGE from dub004-omc4s8.hotmail.com[157.55.2.83]: 4.7.1 Service unavailable - try again later; from=<dmitry.macarov@hotmail.com> to=<makarov@lankey.ru> proto=ESMTP helo=<DUB004-OMC4S8.hotmail.com>
(This is maillog)
More detailed information from rmilter for clamd:
>Jan 29 21:57:45 mx01 rmilter[53818]: mlfi_eom: F0FA41A459: tempfile=/tmp/msg.XXbvRwza, size=366517
>Jan 29 21:57:46 mx01 rmilter[53818]: clamav: read, 127.0.0.1: Operation now in progress
>Jan 29 21:57:46 mx01 rmilter[53818]: clamscan: failed to scan, retry, 127.0.0.1, /tmp/msg.XXbvRwza
>Jan 29 21:57:47 mx01 rmilter[53818]: clamav: read, 127.0.0.1: Operation now in progress
>Jan 29 21:57:47 mx01 rmilter[53818]: clamscan: failed to scan, retry, 127.0.0.1, /tmp/msg.XXbvRwza
>Jan 29 21:57:48 mx01 rmilter[53818]: clamav: read, 127.0.0.1: Operation now in progress
>Jan 29 21:57:48 mx01 rmilter[53818]: clamscan: failed to scan, retry, 127.0.0.1, /tmp/msg.XXbvRwza
>Jan 29 21:57:49 mx01 rmilter[53818]: clamav: read, 127.0.0.1: Operation now in progress
>Jan 29 21:57:49 mx01 rmilter[53818]: clamscan: failed to scan, retry, 127.0.0.1, /tmp/msg.XXbvRwza
>Jan 29 21:57:50 mx01 rmilter[53818]: clamav: read, 127.0.0.1: Operation now in progress
>Jan 29 21:57:50 mx01 rmilter[53818]: clamscan: retry limit exceeded, 127.0.0.1, /tmp/msg.XXbvRwza
>Jan 29 21:57:50 mx01 rmilter[53818]: clamscan: scan 4.127258, 127.0.0.1, /tmp/msg.XXbvRwza
>Jan 29 21:57:50 mx01 rmilter[53818]: mlfi_eom: F0FA41A459: check_clamscan() failed, -1

and for each this try clamd return result that virus founded:
>Fri Jan 29 21:57:46 2016 -> stream(127.0.0.1@1125): Block.EXE-zip.UNOFFICIAL(cec4ee487e4770cdee46ca252ffe4f3e:366517) FOUND
>Fri Jan 29 21:57:47 2016 -> stream(127.0.0.1@1562): Block.EXE-zip.UNOFFICIAL(cec4ee487e4770cdee46ca252ffe4f3e:366517) FOUND
>Fri Jan 29 21:57:48 2016 -> stream(127.0.0.1@1911): Block.EXE-zip.UNOFFICIAL(cec4ee487e4770cdee46ca252ffe4f3e:366517) FOUND
>Fri Jan 29 21:57:49 2016 -> stream(127.0.0.1@1470): Block.EXE-zip.UNOFFICIAL(cec4ee487e4770cdee46ca252ffe4f3e:366517) FOUND
>Fri Jan 29 21:57:50 2016 -> stream(127.0.0.1@1592): Block.EXE-zip.UNOFFICIAL(cec4ee487e4770cdee46ca252ffe4f3e:366517) FOUND

**Comment by vstakhov** [comment]
I see, I'll work on a fix soon. I'd like to say sorry for so many problems with this code - it is very old and I don't use clamav anywhere. So I have to rely on users' testing only.

**Comment by damned-trooper** [comment]
Thanks a lot.
I will waiting for fix.

**Comment by vstakhov** [comment]
Well, I've added the appropriate fix to read the full reply from clamav and not give up.

**Comment by damned-trooper** [comment]
Yes! It works!
Thanks a lot.
