### ISSUE TITLE
Feature Request: Add header X-Spam-Score

### ISSUE THREAD

**Issue by mnik247** [vstakhov/rmilter#79]
In v 1.7.3  
-Add support of X-Spamd-Bar
-Print symbols scores, add SA compaitble headers

It look like:
X-Spamd-Bar: +
X-Spam-Level: **
X-Spam-Status: No, score=1.3

Is it possible add only simple header "X-Spam-Score" with score only? 
It look like:
X-Spam-Score: -2.701

**Comment by vstakhov** [comment]
Is it possible to apply a trivial regexp to X-Spam-Status to extract score? I'm not happy about further polluting of headers produced by rmilter. Number of '*' and '+' should be fixed now.

**Comment by mnik247** [comment]
We not use "X-Spamd-Bar" and "X-Spam-Level" but use Thunderbird with "Column Wizard" and used "X-Spam-Score" as column before rspamd (SpamAssasin).
May be best way is customization "extra headers"?
extra_x_spamd_bar = true|fales;
extra_x-spam_level = true|fales;
extra_x_span_score = true|fales;
Add or not add this headers to message.

**Comment by bax-** [comment]
+1 for making these headers optional.
Just out of curiosity: Why would you need these headers?

**Comment by moisseev** [comment]
There are cases when it is difficult or impossible to compare or sort numeric values, but it is possible to search a substring in the `X-Spamd-Bar:` or `X-Spam-Level:`. E.g. you can use substring `++++` as a threshold that matches `X-Spamd-Bar:` values with 4 or more `+`.

**Comment by bax-** [comment]
@moisseev I understand, thank you very much!

**Comment by mnik247** [comment]
Now is possible add/remove headers.
https://github.com/vstakhov/rspamd/issues/#835
