### ISSUE TITLE
1.7.3 sid debian package is missing rmilter.socket

### ISSUE THREAD

**Issue by skibbipl** [vstakhov/rmilter#81]
Today I switched from my own compiled rmilter & rspamd packages to those from http://rspamd.com/apt-stable/. Unfortunately rmilter package is lacking rmilter.socket systemd socket configuration, therefore you cannot start rmilter after installation.

**Comment by vstakhov** [comment]
I don't have systemd and therefore I have no ways to properly support this tool in rspamd/rmilter. So either send patches or don't use systemd integration. I have neither desire nor possibilities to maintain system specific things.

**Comment by skibbipl** [comment]
When I self compile rmilter on debian the rmilter.socket file is there, so it's not like systemd is broken. It's just missing file in the package. Not a big deal, I just wanted to point that out.

**Comment by vstakhov** [comment]
OK, I've fixed that in the experimental packages line. Manpages were not installed as well...
