### ISSUE TITLE
Never reject e-mails

### ISSUE THREAD

**Issue by nahuelange** [vstakhov/rmilter#82]
Hi,
I just saw in my logs that rmilter rejected a "spam" e-mail, that is not expected by me. To prevent loosing false-positive e-mails I want to put them all in the Spam folder.
So I tried to look for a setting to set large value for rejecting, or disable rejecting and cannot find anything.
I think I couldn't find it, but it exists somewhere.
Can you add this in the doc?

**Comment by moisseev** [comment]
See `spamd_never_reject` in the `spamd` section of the README.md or `man 8 rmilter`.

**Comment by nahuelange** [comment]
Thanks for your quick answer.
I didn't look the README.md, my bad, but FIY I have no rmilter man in the debian packages, and this option is not in the default config file.

**Comment by vstakhov** [comment]
Manpage issue should be fixed.

**Comment by nahuelange** [comment]
Thanks, so this ticket can be closed?
