### ISSUE TITLE
spam_header for authenticated users

### ISSUE THREAD

**Issue by mnik247** [vstakhov/rmilter#84]
rmilter 1.7.4 git 9cfdaec819aaeb865d7ca259cbf5422397110508 (centos 6, postfix)
For authenticated users rmilter set "spam_header"  to "spam_header_value" (but not add extended_spam_headers)
Example:
Received: from [192.168.1.196] (host-126-6-5-39.la.net [126.6.5.39])
	(Authenticated sender: serg@domain.com)
	by zm.domain.com (Postfix) with ESMTPSA id 0267A8009F
	for <serg@domain.com>; Wed, 17 Feb 2016 20:15:21 +0200 (EET)
Date: Wed, 17 Feb 2016 20:01:14 +0200
Subject: Home-akadem
From: Sergey <serg@domain.com>
To: Serega <serg@domain.com>
Importance: Normal
X-Priority: 3
X-MSMail-Priority: Normal
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="--_com.android.email_1025802359134463"
Message-Id: <20160217181522.0267A8009F@zm.domain.com>
X-Spam-Flag: YES

maillog:
Feb 17 20:15:21 zm postfix/smtps/smtpd[3599]: connect from host-126-6-5-39.la.net[126.6.5.39]
Feb 17 20:15:21 zm postfix/smtps/smtpd[3599]: Anonymous TLS connection established from host-126-6-5-39.la.net[126.6.5.39]: TLSv1.2 with cipher ECDHE-
RSA-AES128-GCM-SHA256 (128/128 bits)
Feb 17 20:15:21 zm rmilter[13932]: mlfi_envfrom: client is authenticated as: serg@domain.com
Feb 17 20:15:22 zm postfix/smtps/smtpd[3599]: NOQUEUE: filter: RCPT from host-126-26-25-39.la.net[126.6.5.39]: <serg@domain.com>: Sender address tri
ggers FILTER smtp-amavis:[127.0.0.1]:10026; from=<serg@domain.com> to=<serg@domain.com> proto=ESMTP helo=<[192.168.1.196]>
Feb 17 20:15:22 zm postfix/smtps/smtpd[3599]: 0267A8009F: client=host-126-6-5-39.la.net[126.6.5.39], sasl_method=PLAIN, sasl_username=serg@domain.com
Feb 17 20:15:22 zm postfix/cleanup[378]: 0267A8009F: message-id=<20160217181522.0267A8009F@zm.domain.com>
Feb 17 20:15:22 zm rmilter[13932]: mlfi_eom: 0267A8009F: tempfile=/tmp/msg.XXeoHgnK, size=25147
Feb 17 20:15:22 zm rmilter[13932]: spamdscan: scan qid: <0267A8009F>, mid: <20160217181522.0267A8009F@zm.domain.com>, 0.004415, localhost, 
metric: default: [9.900000 / 19.000000], symbols: R_MISSING_CHARSET(5.00), MIME_GOOD(-0.10), MISSING_MIMEOLE(5.00)
Feb 17 20:15:22 zm rmilter[13932]: mlfi_eom: 0267A8009F: add spam header to message according to spamd action

rspamd.log:
2016-02-17 20:15:22 #5074(normal) <16d723>; task; rspamd_message_parse: loaded message; id: <20160217181522.0267A8009F@zm.domain.com>; queue-id: <0267A80
09F>
2016-02-17 20:15:22 #5074(normal) <16d723>; lua; settings.lua:212: check for settings
2016-02-17 20:15:22 #5074(normal) <16d723>; task; spf_symbol_callback: skip SPF checks for local networks and authorized users
2016-02-17 20:15:22 #5074(normal) <16d723>; task; rspamd_task_write_log: id: <20160217181522.0267A8009F@zm.domain.com>, qid: <0267A8009F>, ip: 126.6.5.
39, user: serg@domain.com, from: <serg@domain.com>, (default: F (add header): [9.90/19.00] [MISSING_MIMEOLE,MIME_GOOD,R_MISSING_CHARSET]), len: 25147
, time: 3.775ms real, 3.464ms virtual, dns req: 1

**Comment by vstakhov** [comment]
Extended headers are not added for authenticated users. That's intended behaviour.

**Comment by mnik247** [comment]
I write about add "spam_header" to "spam_header_value" not "extended_spam_headers"
Я здесь писал не о "extended_spam_headers", а о том, что пропускается "spam_header", если его установил rspamd.

**Comment by vstakhov** [comment]
Erm, I'm still not with you: Russian and English sentences are both cryptic for me. Rspamd **does not** set any headers. What do you mean by 'missing spam_header if it was set by rspamd'?

**Comment by mnik247** [comment]
rmilter.conf.common:
# spam_header - add specified header if action is add_header and spamd_soft_fail os turned on
spam_header = "X-Spam-Flag";
# spam_header_value - add specified value for spam_header
spam_header_value = "YES";

Email headers from  authenticated users (above full headers):
Message-Id: 20160217181522.0267A8009F@zm.domain.com
X-Spam-Flag: YES

maillog:
Feb 17 20:15:22 zm rmilter[13932]: mlfi_eom: 0267A8009F: add spam header to message according to spamd action

"spam header" should not be add, similar to  "extended_spam_headers".

**Comment by vstakhov** [comment]
That's also an expected pattern. Spam header is added to make a hint for remote MTA whilst the exact spam report is hidden.

**Comment by mnik247** [comment]
I don't think remote MTA know about my "spam_header"...
Is it possible rmilter not add "spam_header" for "authenticated users"?
Or is it possible add "custom score" for "authenticated users" in rspamd?

**Comment by vstakhov** [comment]
You can turn off all checks in rmilter for authenticated users by setting `strict_auth = no`

**Comment by mnik247** [comment]
I want check emails from "authenticated users" and see it in web-ui and logs (if my clients will hacked).
But I don't want add "spam_header" from "authenticated users".
Is it possible add "custom score" for "authenticated users" in rspamd?

**Comment by vstakhov** [comment]
I have opposite requests: one to keep the current logic and one to remove it. I don't know what to do. I can add some more flags to config, perhaps...

**Comment by mnik247** [comment]
"I can add some more flags to config, perhaps..." - the bast way.

**Comment by mnik247** [comment]
Thanks.
I will try it.

**Comment by mnik247** [comment]
Thanks,
spam_no_auth_header = yes;
And rmilter not add "spam_header" for "authenticated users"

**Comment by moisseev** [comment]
@vstakhov  But `spam_no_auth_header` seems pretty counterintuitive. I like postfix configuration parameters style. They are a bit lengthy but very descriptive and readable.
What about something like `spam_header_unauth_only`?

**Comment by vstakhov** [comment]
On the other hand, your proposition inverses the logic of this flag which I don't like. I do agree that options in rmilter are confusing and stupid. I need to find some time and throw lex/yacc away and do everything based on libucl, where you can set aliases for unfortunate options.
