### ISSUE TITLE
greylisting headers

### ISSUE THREAD

**Issue by mnik247** [vstakhov/rmilter#85]
Is it correct headers?
X-Rmilter-Greylist: Greylisted for 306 seconds, whitelisted till 2016-02-21 17:22:24, type: sender, IP, recipients
X-Rmilter-Greylist: Sender IP 0 is whitelisted by configuration

**Comment by vstakhov** [comment]
The first one is correct, the second one is bugged

**Comment by mnik247** [comment]
Thanks.
I will try it.

**Comment by mnik247** [comment]
"X-Rmilter-Greylist: Sender IP 0 is whitelisted by configuration" - fixed, thanks.

Is it possible to log more info?
Feb 18 19:19:28 zm rmilter[15873]: greylisting_check_hash: greylisted <E915180092>: 0 seconds passed, greylisted till 2016-02-18 19:24:28, type: sender, IP,
recipients
I'd like see details of hash: IP, sender, recipients.
May be add more info in "greylisting header" too?

**Comment by mnik247** [comment]
And is it correct log?
Feb 18 19:29:10 zm rmilter[15873]: greylisting_check_hash: greylisted <CECCC80092>: 0 seconds passed, greylisted till 2016-02-18 19:34:10, type: data hash
Feb 18 19:29:10 zm rmilter[15873]: greylisting_check_hash: greylisted <CECCC80092>: 314956774 seconds passed, greylisted till 4429407-04-28 13:49:16, type: s
ender, IP, recipients

I mean about date "4429407-04-28 13:49:16"

**Comment by mnik247** [comment]
"greylisting headers" not insert if  X-Spamd-Result: default: True [19.29 / 19.00]
I used now 
spamd_never_reject= yes;
And all "virtaul rejected" emails  not contain "greylisting headers".

**Comment by mnik247** [comment]
After last commit 3074cddd3e0b228771788931904bd98fc9d72657 
1) "virtaul rejected" emails contain normal "greylisting headers"
2) BUT drop add "spam_header" for "virtaul rejected" emails.

**Comment by vstakhov** [comment]
Should be fixed now.

**Comment by mnik247** [comment]
Thanks,
Fixed now.
