### ISSUE TITLE
[help please] not dkim sign for outgoing mails

### ISSUE THREAD

**Issue by guidtz** [vstakhov/rmilter#92]
Hello,

  can I ask you help. I don't know why but my milter don't sign outgoing mail for authorized users.

My configuration : Debian 8
rmilter version : 1.6.1
rspamd version : 0.6.10

rmilter.conf : 
``
dkim {
    domain {
      key = /etc/dkim/mydomain/mydomain.201603050951.key;
      domain = "mydomain";
      selector = "201603050951";
      };
    header_canon = relaxed;
    body_canon = relaxed;
    sign_alg = sha256;
    auth_only = no;
};
``

postfix main.cf : 
``
smtpd_milters = inet:localhost:11000
milter_protocol = 6
milter_mail_macros = i {mail_addr} {client_addr} {client_name} {auth_authen}
milter_rcpt_macros = i {rcpt_addr}
milter_default_action = accept
``

postfix master.cf : 
``
smtps     inet  n       -       -       -       -       smtpd
  -o syslog_name=postfix/smtps
  -o smtpd_tls_wrappermode=yes
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_sasl_type=dovecot
  -o smtpd_sasl_path=private/auth
  -o smtpd_sasl_security_options=noanonymous
  -o smtpd_sasl_local_domain=$myhostname
  -o smtpd_client_restrictions=permit_sasl_authenticated,reject
  -o smtpd_sender_restrictions=reject_sender_login_mismatch
  -o smtpd_recipient_restrictions=reject_non_fqdn_recipient,reject_unknown_recipient_domain,permit_sasl_authenticated,reject
  -o smtpd_milters=inet:localhost:11000
  -o milter_protocol=6
  -o milter_default_action=accept
``

Thanks for you're help

**Comment by vstakhov** [comment]
Your versions are more than one year old. They are not supported. Please use the packages provided on https://rspamd.com site.

**Comment by guidtz** [comment]
Hello I update all : 
rmilter                        1.7.5-1~jessie 
rspamd                         1.1.4-1~jessie

When I send a mail I have this : 
**spam scan: skipped, whitelisted; virus scan: clean; dkim: not signed, ignored**

**Comment by vstakhov** [comment]
Yes, becase your SMTP session is likely authenticated and rmilter skips checking of such a mail messages by default. DKIM requires keys setup which is all descrinbed in the documentation.

**Comment by SavageCore** [comment]
I have 

```
dkim {
    domain {
      key = /etc/opendkim/keys;
      domain = "*";
      selector = "dkim";
    };
    header_canon = relaxed;
    body_canon = relaxed;
    sign_alg = sha256;
};
```

`ls -l /etc/opendkim/keys:`
```
-rw------- 1 root root 887 Mar 31 16:12 websites4villages.co.uk.dkim.key
-rw------- 1 root root 321 Mar 31 16:12 websites4villages.co.uk.dkim.txt
```

spam scan: skipped, whitelisted; virus scan: skipped, no av servers; **dkim: not signed, ignored**

What more needs configuring to sign?

**Comment by vstakhov** [comment]
Are you trying to check messages for authenticated users?

**Comment by SavageCore** [comment]
Yes

**Comment by SavageCore** [comment]
In `main.cf`

```
# rmilter setup
smtpd_milters = inet:localhost:9900
milter_default_action = accept
milter_protocol = 6
milter_mail_macros = i {mail_addr} {client_addr} {client_name} {auth_authen}
```

**Comment by vstakhov** [comment]
Then maybe rmilter don't have sufficient permissions to read keys?

**Comment by SavageCore** [comment]
That was it thanks. Perhaps @guidtz has the same issue.
