### ISSUE TITLE
Problems with "rspamd_metric"

### ISSUE THREAD

**Issue by dnl555** [vstakhov/rmilter#93]
Hi, 

I’m using rmilter 1.7.5-1 and rspamd version 1.1.4-1 and I’m confused with a problem with the directive rspamd_metric in rmilter.conf . 
I create 2 metrics for my rspamd cluster ( One with specific rules for Inbound and another one with specific rules for outbound ) . Each one with different scores for “reject” and “add_header” .  

After that, I configured the rmilter in my servers to check only the outbound metrics : 

spamd{
	rspamd_metric = "outbound";
	.
	.
	.

But in the scans the metric checked by rmilter is just the default .  The scores that I configured in outbound metric are being ignored. 

If I run rspamc locally in rspamd cluster, both metrics are checked . 

root@debian8:~# rspamc < mensagem
Results for file: stdin (0.865 seconds)
[Metric: outbound]
Spam: false
Score: -0.10 / 150.00
Action: no action
Symbol: BAYES_SPAM (0.00)[100.00%]
Symbol: MIME_GOOD (-0.10)[text/plain]
Symbol: URIBL_BLOCKED [Metric: default]
Spam: false
Score: 3.89 / 15.00
Action: no action
Symbol: BAYES_SPAM (4.00)[100.00%]
Symbol: MIME_GOOD (-0.10)[text/plain]
Symbol: URIBL_BLOCKED 
Message-ID: 20160315173225.18D6643826@debian8.com.br

Someone already had this problem?

**Comment by fatalbanana** [comment]
You may find that you can achieve what you want with settings module: https://rspamd.com/doc/configuration/settings.html

**Comment by vstakhov** [comment]
Well, the idea of metrics wasn't quite good and it haven't been used anywhere. What I think is better to do is to create a sort of so called `sets` where each set has its own list of rules, scores and actions. Then, a client should be able to specify the desired set on scan, so rmilter could scan both income and outcome messages by just specifying the desired set.

**Comment by dnl555** [comment]
Thanks fatalbanana / vstakhov . 

Works like a charm with "settings" module \o .
