### ISSUE TITLE
[help request] Explanation of overall concept?

### ISSUE THREAD

**Issue by Binarus1** [vstakhov/rmilter#94]
Hello,

I think I have understood how to configure rmilter (thank you very much for the excellent man page). But I don't seem to be able to grasp the overall concept, notably how the different checks are playing together.

For example, if one check fails, but a later check would succeed for a certain triple of connection / message / recipient, what happens? Does rmilter give a REJECT to Sendmail after the first check which fails?

I would like to deploy (envelope) recipient whitelists, SPF and DKIM according to the following logic (pseudocode):

```
for each connection

  for each message

    for each envelope recipient

      if (current recipient in RCPT-TO-whitelist)
        accept current message and deliver it to all RCPT TO recipients
      end if

    end for

    if (MAIL-FROM-domain has SPF-record)

      if (Connection data matches SPF-record)
        accept current message and deliver it to all RCPT TO recipients
      else
        reject current message
      end if

    else if (MAIL-FROM-domain has DKIM record)

      if (DKIM signature of current message is valid)
        accept current message and deliver it to all RCPT TO recipients
      else
        reject current message
      end if

    end if

    reject current message

  end for

end for
```

Is this possible with rmilter (or multiple running instances of rmilter)?

Thank you very much,

Binarus

**Comment by fatalbanana** [comment]
Rmilter is intended as little else than a shim between Rspamd and milter-capable MTAs such as Postfix.

Contemporary versions of rmilter do not support SPF directly (as this is done in rspamd). DKIM support is merely for signing.

Whitelisting can be done in rspamd (based on SPF/DKIM/DMARC/other) but will produce one result per SMTP transaction (so you will need to see that recipients are limited/batched appropriately).

**Comment by Binarus1** [comment]
To answer my own question: I have solved my problem by chaining multiple other milters. I didn't want to learn rspamd's configuration which seems to be fairly complex.
