### ISSUE TITLE
2 errors

### ISSUE THREAD

**Issue by MisterM74** [vstakhov/rmilter#95]
Hello
2 errors, the first when I configure with this line under postfix, and rmilter start, I have this error message that appears.
`warning: connect to Milter service unix:/var/run/rmilter/rmilter.sock: No such file or directory`
And the second, when I send a message and my domain is signed, I also have this error message that appears.
`rmilter[17262]: msg done: 126D54200AAC: ip: 74.125.82.44; from: info@domain.tv; rcpt: <mich@domain.be> (1 total); user: unauthorized; spam scan: no spam; virus scan: clean; dkim: not signed, ignored`

thanks for your help
Michel

**Comment by vstakhov** [comment]
Fro the first issue you could use TCP sockets instead of unix ones. For the second issue you should either use rmilter for SMTP authorized sessions or setup `sign_networks` in `dkim` section (please refer to the corresponding documentation)

**Comment by MisterM74** [comment]
`Fro the first issue you could use TCP sockets instead of unix ones.`
OK 
`For the second issue you should either use rmilter for SMTP authorized sessions or setup sign_networks in dkim section (please refer to the corresponding documentation)`

Do I need to add this?
`sign_networks = empty`

If so, this is spit rmilter
`Mar 30 18:45:24 smtp rmilter[8674]: config file parse error! line: 257, text: empty, reason: syntax error
Mar 30 18:45:24 smtp rmilter[8674]: yyparse: cannot parse config file, 1 errors
Mar 30 18:45:24 smtp kernel: [369571.610912] init: rmilter main process (8674) terminated with status 9`

Mz

**Comment by vstakhov** [comment]
You need to add list of networks for which rmilter should sign messages. By default, it signs merely messages for authenticated users (and that's not your case).

**Comment by MisterM74** [comment]
Or it is the configuration that you say?

Thank you

Michel
