### ISSUE TITLE
memory corruption

### ISSUE THREAD

**Issue by damned-trooper** [vstakhov/rmilter#96]
Hi.
Today i got strange error from rmilter.
rmilter service was active, but milter did not accept connection on socket. 
From /var/log/messages:
```
Apr 14 03:47:42 mx02n rmilter: *** Error in `/usr/sbin/rmilter': malloc(): memory corruption: 0x00007fe6148b3690 ***
Apr 14 03:47:43 mx02n rmilter: *** Error in `/usr/sbin/rmilter': malloc(): memory corruption: 0x00007fe6148b3690 ***
Apr 14 03:47:47 mx02n rmilter: *** Error in `/usr/sbin/rmilter': malloc(): memory corruption: 0x00007fe6148b3690 ***
Apr 14 03:47:48 mx02n rmilter: *** Error in `/usr/sbin/rmilter': malloc(): memory corruption: 0x00007fe6148b3690 ***
Apr 14 03:47:48 mx02n rmilter: *** Error in `/usr/sbin/rmilter': malloc(): memory corruption: 0x00007fe6148b3690 ***
```
From journalctl:
```
Apr 14 06:29:40 mx02n.lancloud.ru rmilter[4852]: rmilter: Unable to set close-on-exec on connfd (Bad file descriptor)
Apr 14 06:29:40 mx02n.lancloud.ru rmilter[4852]: rmilter: Unable to set close-on-exec on connfd (Bad file descriptor)
Apr 14 06:29:40 mx02n.lancloud.ru rmilter[4852]: rmilter: Unable to set close-on-exec on connfd (Bad file descriptor)
```
From postfix:
```
Apr 14 07:46:47 mx02n.lancloud.ru postfix-in/smtpd[60352]: warning: milter inet:127.0.0.1:9900: can't read SMFIC_OPTNEG reply packet header: Connection timed
Apr 14 07:46:47 mx02n.lancloud.ru postfix-in/smtpd[60352]: warning: milter inet:127.0.0.1:9900: read error in initial handshake
```

Is there a way to understand what happened?

**Comment by vstakhov** [comment]
I need coredumps for further investigations I suppose: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed

**Comment by damned-trooper** [comment]
Hi.
I turned on coredump and will send you results after the next crash.
And one more question - could you please fix documentation about coredumps?
In the linux senction actual settings are:
**/etc/sysctl.conf**
```
kernel.core_uses_pid = 1
kernel.core_pattern = /coreland/%e-%p.core
fs.suid_dumpable = 2
```

And for systemd based distros additional configs (need run systemctl daemon-reexec for apply):
**/etc/systemd/system.conf**
```
DefaultLimitCORE=infinity
```
and this for each service:
```
[Service]
LimitCORE=unlimited
```

I can write more detailed text about it.

**Comment by vstakhov** [comment]
That would be greately appreciated! I have no experiences with systemd and it looks cryptic to me.

**Comment by damned-trooper** [comment]
For the part of https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed "How to figure out why rspamd process crashed"

------ Original text ------
How to figure out why rspamd process crashed
Like other programs written in C language, the best way to debug these problems is to obtain core dump. Unfortunately, there is no universal solution suitable for all platforms, however, for FreeBSD and Linux you could do the following.

First of all, you’d need to create a special directory for core files that will be allowed for writing for all users in the system:

```
mkdir /coreland
chmod 1777 /coreland
```
For FreeBSD you can have either one core for all processes by setting:
`sysctl kern.corefile=/coreland/%N.core`
or a separated core for each crash (that includes PID of process):
`sysctl kern.corefile=/coreland/%N-%p.core`
------ Original text ------
------ Fix started ------
For Linux this setting is slightly different:
`sysctl kernel.core_pattern = /coreland/%e.core`
or
`sysctl kernel.core_pattern = /coreland/%e-%p.core`

Additional settings:
```
sysctl kernel.core_uses_pid = 1
sysctl fs.suid_dumpable = 2
```
first one added PID to core file name, and second allowed setuid processes to be dumped.
A good idea is add this settings to `/etc/sysctl.conf` and then run `sysctl -p` for apply.

In case of distro with systemd (most mainstream Linux distros) there are additional settings.
First you need edit file `/etc/systemd/system.conf` and uncomment `DefaultLimitCORE` parameter and set it to `infinity` (`DefaultLimitCORE=infinity`) to enable systemd coredumping. After this you need run `systemctl daemon-reload` to reread configuration and then `systemstl daemon-reexec` to apply it.
Second you need edit limit of coredumps for services. You must edit service unit and add parameter `LimitCORE=unlimited` to `[Service]` section of unit (in theory `DefaultLimitCORE` option enought, but in practice you may need to forcibly set `LimitCORE` for each service). A good practice is to add overrides to user file, which located at `/etc/systemd/system/`, becaues original unit-file will be replaced after upgrade.
After unit-file was changed you need to run `systemctl daemon-reload` and then `systemctl restart rmilter.service` or `systemctl restart rspamd.service`.

In distros with old SysV init you can use service init file, for example `/etc/init.d/rspamd` to permit dumping of core files by setting the appropriate resource limit. You need add line `ulimit -c unlimited` just after the heading comment.
In FreeBSD you can use `/usr/local/etc/rc.d/rspamd` file same way.

A good way to test this is send SIGILL (in Linux - 4) to process. For example run `pkill --signal 4 rspamd` or `kill -s 4 <YOUR_PID>` and then check `/coreland` directory for dump.
------ Fix ended ------

**Comment by vstakhov** [comment]
That's perfect, thank you!
