### ISSUE TITLE
dkim: not signed, ignored

### ISSUE THREAD

**Issue by wangyu1314** [vstakhov/rmilter#97]
hello.
 I use centos 6.7 x64 and yum install rmilter 1.7.5.1 and rsapmd 1.2.3.1
I config the rmilter.conf.common file, and below is the dkim fields:

    domain {
		key = /etc/opendkim/keys/cnprint.org/20160322.private;
		domain = "cnprint.org";
		selector = "20160322";
	};
    header_canon = relaxed;
    body_canon = relaxed;
    sign_alg = sha256;
    auth_only = yes;
};

opendkim use this key "/etc/opendkim/keys/cnprint.org/20160322.private" is ok, but rmilter can't work,  I have done
chown _rmilter:_rspamd /etc/opendkim/keys/cnprint.org/20160322.private 

below is the error log:
Apr 17 21:12:35 mail rmilter[17169]: msg done: D62B72143B: ip: 119.147.115.162; from: admin@cnprint.org; rcpt: <lixinwelldone@sina.com> (1 total); user: admin@cnprint.org; spam scan: skipped, whitelisted; virus scan: skipped, no av servers; dkim: not signed, ignored

could you help me, thank you.

**Comment by vstakhov** [comment]
Does it work when you configure your key to work in wildcard mode?

**Comment by wangyu1314** [comment]
Now I create a new directory is /etc/dkim , and copy the flie  /etc/opendkim/keys/cnprint.org/20160322.private into it and rename as cnprint.org.20160322.key.
so my config files is changed:
    domain {
		key = /etc/dkim/cnprint.org.20160322.key;
		domain = "cnprint.org";
		selector = "20160322";
	};
    header_canon = relaxed;
    body_canon = relaxed;
    sign_alg = sha256;
    auth_only = yes;
};
after that
chown -R _rmilter:_rspamd /etc/dkim/*
chmod 550 /etc/dkim
chmod 640 /etc/dkim/*   
service postfix restart
service rmilter restart.
DKIM can't work yet and can't work in wildcard mode.

**Comment by wangyu1314** [comment]
NOW I yum upgrade to rmilter 1.8.0, dkim is work fine. the config flies as same as  old 1.7.5.
thank you much, have a good day. @vstakhov 

Apr 21 10:40:06 mail rmilter[20528]: msg done: 8FDD3235B4: ip: 119.147.115.162; from: admin@cnprint.org; rcpt: <296417057@qq.com> (1 total); user: admin@cnprint.org; spam scan: skipped, whitelisted; virus scan: skipped, no av servers; dkim: signed
