### ISSUE TITLE
mkstemp failed: Too many open files

### ISSUE THREAD

**Issue by episodeiv** [vstakhov/rmilter#98]
I've installed rspamd-1.2.3/rmilter-1.7.5 on a relatively quiet mailing system using postfix and face the following problem every couple of hours.

rmilter logs the following:
> Apr 22 18:21:54 ridcully rmilter[21609]: create_temp_file: 8D94C340D8: mkstemp failed: Too many open files

When I check lsof, I see more than 3000 opened fds for rmilter, almost all of them open socket connections. I've tried switching rmilter from using unix sockets to a tcp socket but that did not help.

Restarting rmilter fixes the problem temporarily (the fd count right after launch is at about 150). For now, I've raised the ulimit -n for rmilter but am wondering if that number seems reasonable or if something along the way isn't closing these connections properly.

Cheers,
Dennis

**Comment by vstakhov** [comment]
The most recent version of rmilter is `1.8.1`.

**Comment by episodeiv** [comment]
Sorry, just saw that my distribution wasn't up to date so I updated manually to 1.8.1. It's only been running for a couple of minutes but I already see steadily increasing fd counts.

**Comment by vstakhov** [comment]
Is it the default configuration?

**Comment by episodeiv** [comment]
Except for 

> extended_spam_headers = yes;

and

> spamd_greylist = no;

As I wrote, I tried changing the bind_socket to inet:11300@127.0.0.1 which didn't make any difference.

**Comment by vstakhov** [comment]
So, no clamav, just rspamd + redis, correct?

**Comment by episodeiv** [comment]
No clamav, but no redis either right now. So just rspamd + sqlite.

**Comment by vstakhov** [comment]
Then maybe it is related to absence of redis. Let me check...

**Comment by vstakhov** [comment]
Could you please apply this patch and test if your issue is resolved?

**Comment by episodeiv** [comment]
It looks indeed like a redis problem. I temporarily whipped up a redis instance and the fd count remained constant.
I've applied your patch and am running the patched version right now. I'll report back once I get some reliable numbers.

**Comment by episodeiv** [comment]
The patch seems to work great, no more fd leaks!
Thanks!
